### PR TITLE
maintain access to tiers removed from TTL

### LINKED ISSUE #13449: CS fails when Tier  deleted
When a tier is removed from TTL settings in Column Store that has data evicted to that tier, CS crashes on actions that try to access that data.

VERIFY failed (2025-01-16T14:05:26.629384Z): tablet_id=72075186224037909;task_id=ef9bbe88-d41211ef-ab34c9f5-6566138c;tablet_id=72075186224037909;queue=ttl;external_count=0;verification=info;fline=tiering.cpp:181;
  ydb/library/actors/core/log.cpp:754
  ~TVerifyFormattedRecordWriter(): requirement false failed
0. /-S/util/system/yassert.cpp:83: InternalPanicImpl @ 0x9BAF62A
1. /-S/util/system/yassert.cpp:55: Panic @ 0x9BA8B96
2. /tmp//-S/ydb/library/actors/core/log.cpp:754: ~TVerifyFormattedRecordWriter @ 0xA938D83
3. /tmp//-S/ydb/core/tx/columnshard/engines/storage/actualizer/tiering/tiering.cpp:181: DoExtractTasks @ 0x107D113C
4. /-S/ydb/core/tx/columnshard/engines/storage/actualizer/abstract/abstract.h:20: ExtractTasks @ 0x107C7C92
5. /tmp//-S/ydb/core/tx/columnshard/engines/storage/actualizer/index/index.cpp:11: ExtractActualizationTasks @ 0x107C7C92
6. /tmp//-S/ydb/core/tx/columnshard/engines/storage/granule/granule.cpp:169: BuildActualizationTasks @ 0x107B8B79
7. /tmp//-S/ydb/core/tx/columnshard/engines/column_engine_logs.cpp:439: StartTtl @ 0x125013AC
8. /tmp//-S/ydb/core/tx/columnshard/columnshard_impl.cpp:1001: SetupTtl @ 0x126A2482
9. /tmp//-S/ydb/core/tx/columnshard/columnshard_impl.cpp:530: EnqueueBackgroundActivities @ 0x1269E42C
10. /tmp//-S/ydb/core/tx/columnshard/blobs_action/transaction/tx_write_index.cpp:68: Complete @ 0x125D4FF8
11. /tmp//-S/ydb/core/tablet_flat/flat_exec_seat.cpp:11: Complete @ 0xC5997ED
12. /tmp//-S/ydb/core/tablet_flat/flat_executor_txloglogic.cpp:279: Confirm @ 0xC593B3B
13. /tmp//-S/ydb/core/tablet_flat/flat_executor.cpp:2924: Handle @ 0xC4F8AA1
14. /tmp//-S/ydb/core/tablet_flat/flat_executor.cpp:3938: StateWork @ 0xC4D80A9
15. /tmp//-S/ydb/library/actors/core/executor_thread.cpp:281: Execute @ 0xA92AB34

### LINKED ISSUE #13469: VERIFY failed on eviction to tier with not ready storage manager
VERIFY failed in tiering scenario test
https://paste.yandex-team.ru/750a2dcf-167f-4627-ba90-7b067dfb3a4f

### PR DESCRIPTION
**Pull request by swalrus1**
### Changelog entry 

Maintain access to populated tiers removed from TTL on CS

### Changelog category 

* Improvement
* Bugfix 

### Additional information

...

### CODE REVIEW

File: ydb/core/tx/tiering/manager.h [hunk 1]
```diff
@@ -45,29 +47,48 @@ class TManager {
...
+            return !!Config;
+        }
+
+        const NTiers::TTierConfig& GetConfigVerified() const {
+            return *TValidator::CheckNotNull(Config);
         }
 
-        TTierRefGuard(const NTiers::TExternalStorageId& tierId, TTiersManager& owner);
-        ~TTierRefGuard();
+        void UpsertConfig(NTiers::TTierConfig config) {
```
Comment (ivanmorozov333) [inline ydb/core/tx/tiering/manager.h:66]: &&

File: ydb/core/tx/tiering/manager.h [hunk 2]
```diff
@@ -83,19 +104,14 @@ class TTiersManager: public ITiersManager {
...
-    YDB_READONLY_DEF(TTierById, TierConfigs);
+    using TTierById = THashMap<NTiers::TExternalStorageId, TTierGuard>;
+    YDB_READONLY_DEF(TTierById, Tiers);
     YDB_READONLY_DEF(std::shared_ptr<NMetadata::NSecret::TSnapshot>, Secrets);
 
 private:
     void OnConfigsUpdated(bool notifyShard = true);
-    void RegisterTier(const NTiers::TExternalStorageId& name);
-    void UnregisterTier(const NTiers::TExternalStorageId& name);
+    void RegisterTierManager(const NTiers::TExternalStorageId& name, std::optional<NTiers::TTierConfig> config);
```
Comment (ivanmorozov333) [inline ydb/core/tx/tiering/manager.h:113]: &&

File: ydb/core/tx/tiering/manager.h [hunk 3]
```diff
@@ -105,12 +121,11 @@ class TTiersManager: public ITiersManager {
...
     }
     TActorId GetActorId() const;
-    void EnablePathId(const ui64 pathId, const THashSet<NTiers::TExternalStorageId>& usedTiers);
-    void DisablePathId(const ui64 pathId);
+    void ActivateTiers(const THashSet<NTiers::TExternalStorageId>& usedTiers);
 
     void UpdateSecretsSnapshot(std::shared_ptr<NMetadata::NSecret::TSnapshot> secrets);
-    void UpdateTierConfig(const NTiers::TTierConfig& config, const NTiers::TExternalStorageId& tierId, const bool notifyShard = true);
-    bool AreConfigsComplete() const;
+    void UpdateTierConfig(std::optional<NTiers::TTierConfig> config, const NTiers::TExternalStorageId& tierId, const bool notifyShard = true);
```
Comment (ivanmorozov333) [inline ydb/core/tx/tiering/manager.h:127]: &&

**Review by ivanmorozov333 — APPROVED** [review]
