### PR TITLE
Fix that replication is not reading from splitted partitions when topic auto-partitioning enabled

### LINKED ISSUE #30460: Fix that replication is not reading from splitted partitions when topic auto-partitioning enabled
Проблема была здесь добавлена: https://github.com/ydb-platform/ydb/commit/ce2ff0af5315539e89de99db65b4ceecf5149c2d

До изменений DataEnd пересылался из воркера в родителя воркера, родитель пересылал в контроллер, а контроллер выдавал поспличенные партиции, из которых продолжалось чтение.

В этих изменениях DataEnd пересылается из воркера врайтеру, и тот завершается так как данные в ридере закончились

Предлагаемый фикс: откатить, чтобы DataEnd слался родителю как и раньше. TEvDataEnd, который сейчас приходит во врайтера заменить на какое-то новое событие, которое в репликации слаться не будет

### PR DESCRIPTION
**Pull request by pixcc**
### Changelog entry 

Fixes [30460](https://github.com/ydb-platform/ydb/issues/30460)

### Changelog category 

* Bugfix

### CODE REVIEW

**Review by nshestakov — APPROVED** [review]

File: ydb/core/tx/replication/service/worker.h [hunk 1]
```diff
@@ -86,7 +87,13 @@ struct TEvWorker {
...
 
         TEvDataEnd(ui64 partitionId, TVector<ui64>&& adjacentPartitionsIds, TVector<ui64>&& childPartitionsIds);
-        TEvDataEnd(ui64 partitionId, const TVector<ui64>& adjacentPartitionsIds, const TVector<ui64>& childPartitionsIds);
+        TString ToString() const override;
+    };
+
+    struct TEvTerminateWriter: public TEventLocal<TEvTerminateWriter, EvTerminateWriter> {
+        ui64 PartitionId;
+
+        TEvTerminateWriter(ui64 partitionId);
```
Comment (CyberROFL) [inline ydb/core/tx/replication/service/worker.h:96]:
```suggestion
        explicit TEvTerminateWriter(ui64 partitionId);
```

**Review by CyberROFL — APPROVED** [review]

File: ydb/core/tx/replication/service/worker.h (hunk 1 above)
Comment (pixcc) [reply ydb/core/tx/replication/service/worker.h:96]: https://github.com/ydb-platform/ydb/pull/31110
