### PR TITLE
Fix TExportToS3WithRebootsTests CancelShouldSucceedOnManyTables test after auto dropping

### LINKED ISSUE #16480: Fix tests after autodropping
- [ ] Тест CheckProgress
- [ ] Два теста с таймаутом

### PR DESCRIPTION
**Pull request by stanislav-shchetinin**
### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

...

### CODE REVIEW

File: ydb/core/tx/schemeshard/schemeshard_export__create.cpp [hunk 1]
```diff
@@ -554,6 +554,13 @@ struct TSchemeShard::TExport::TTxProgress: public TSchemeShard::TXxport::TTxBase
         Send(Self->TxAllocatorClient, new TEvTxAllocatorClient::TEvAllocate(), 0, exportInfo->Id);
     }
 
+    void PrepareAutoDropping(TSchemeShard* ss, TExportInfo::TPtr exportInfo, NIceDb::TNiceDb& db) {
+        PrepareDropping(ss, exportInfo, db, TExportInfo::EState::AutoDropping, [&](ui64 itemIdx){
```
Comment (CyberROFL) [inline ydb/core/tx/schemeshard/schemeshard_export__create.cpp:558]:
```suggestion
        PrepareDropping(ss, exportInfo, db, TExportInfo::EState::AutoDropping, [&](ui64 itemIdx) {
```

File: ydb/core/tx/schemeshard/schemeshard_export__create.cpp [hunk 2]
```diff
@@ -805,7 +812,6 @@ struct TSchemeShard::TExport::TTxProgress: public TSchemeShard::TXxport::TTxBase
                     if (item.SourcePathType != NKikimrSchemeOp::EPathTypeTable || item.State != EState::Dropping) {
                         continue;
                     }
-
```
Comment (CyberROFL) [inline ydb/core/tx/schemeshard/schemeshard_export__create.cpp:808]: Лишний дифф.

**Review by CyberROFL — DISMISSED** [review]

**Review by CyberROFL — APPROVED** [review]
