### PR TITLE
Partition at decimal keys

### LINKED ISSUE #10661: Tables with a DECIMAL key column cannot be restored from backups
### Description

Please read the title.

### Steps to reproduce

1. Create a table with a DECIMAL key column and at least 2 partitions:
```sql
create table test_decimal (
    key Decimal(22,9),
    value Utf8,
    primary key(key),
)
with (
    AUTO_PARTITIONING_BY_SIZE = ENABLED,
    AUTO_PARTITIONING_PARTITION_SIZE_MB = 1,
    AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 2
);
```
2. Fill the table so it would be split at least once:
<details>
<summary>huge_value definition</summary>

See the [gist](https://gist.github.com/jepett0/537b077da9aa0de861458048782e3494). Needs to be 100k+ symbols.

</details>

```sql
UPSERT INTO test_decimal (
    key,
    value
)
VALUES
    (CAST(1 as Decimal(22,9)), $huge_value),
    (CAST(2 as Decimal(22,9)), $huge_value),
    (CAST(3 as Decimal(22,9)), $huge_value),
    (CAST(4 as Decimal(22,9)), $huge_value),
    (CAST(5 as Decimal(22,9)), $huge_value),
    (CAST(6 as Decimal(22,9)), $huge_value),
    (CAST(7 as Decimal(22,9)), $huge_value),
    (CAST(8 as Decimal(22,9)), $huge_value),
    (CAST(9 as Decimal(22,9)), $huge_value),
    (CAST(10 as Decimal(22,9)), $huge_value),
    (CAST(11 as Decimal(22,9)), $huge_value),
    (CAST(12 as Decimal(22,9)), $huge_value),
    (CAST(13 as Decimal(22,9)), $huge_value),
    (CAST(14 as Decimal(22,9)), $huge_value),
    (CAST(15 as Decimal(22,9)), $huge_value),
    (CAST(16 as Decimal(22,9)), $huge_value),
    (CAST(17 as Decimal(22,9)), $huge_value),
    (CAST(18 as Decimal(22,9)), $huge_value),
    (CAST(19 as Decimal(22,9)), $huge_value),
    (CAST(20 as Decimal(22,9)), $huge_value);
```
3. Wait for about a minute, so the `test_decimal` table would be split. Check that there are at least 2 partitions in it.
4. Backup to S3 or call `ydb tools dump --path test_decimal --scheme-only --output test_decimal_backup`.
5. Drop the `test_decimal` table.
6. Restore from S3 or call `ydb tools restore --path . --input test_decimal_backup` depending on your choice at step 4.
7. Observe that:
- the export status is CANCELLED:
```text
┌──────────────────────┬───────┬───────────┬───────────┬─────────────────────────┬────────────────────────┐
│ id                   │ ready │ status    │ progress  │ endpoint                │ bucket                 │
├──────────────────────┼───────┼───────────┼───────────┼─────────────────────────┼────────────────────────┤
│ ydb://import/8?id=84 │ true  │ CANCELLED │ Cancelled │ storage.yandexcloud.net │ ydb-backup-test-bucket │
│ 4424930141976&kind=s │       │           │           │                         │                        │
│ 3                    │       │           │           │                         │                        │
├╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴┴╴╴╴╴╴╴╴┴╴╴╴╴╴╴╴╴╴╴╴┴╴╴╴╴╴╴╴╴╴╴╴┴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴┴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴┤
│ Issues:                                                                                                 │
│   - <main>: Error: Error at split boundary 0: Unsupported typeId 4865 at index 0  
```
- or the restore produces an error:
```text
Status: SCHEME_ERROR
Issues: 
<main>: Info: Path: /Root/dedicated/test_decimal
<main>: Error: Error at split boundary 0: Unsupported typeId 4865 at index 0
```

### PR DESCRIPTION
**Pull request by azevaykin**
### Changelog entry 

...

### Changelog category 

* Bugfix 

### Additional information

...

### CODE REVIEW

File: ydb/core/grpc_services/rpc_object_storage.cpp [hunk 1]
```diff
@@ -144,6 +144,15 @@ bool CellFromTuple(NScheme::TTypeInfo type,
         }
         break;
     }
+    case NScheme::NTypeIds::Decimal:
+    {
+        if (tupleValue.Haslow_128()) {
```
Comment (jepett0) [inline ydb/core/grpc_services/rpc_object_storage.cpp:149]: What if Hashigh_128() == false? Would the result of the parsing be correct? Why this place differs from the mkql_proto.cpp case?

**Review by ijon — DISMISSED** [review]

File: ydb/core/grpc_services/rpc_object_storage.cpp (hunk 1 above)
Comment (azevaykin) [reply ydb/core/grpc_services/rpc_object_storage.cpp:149]: https://github.com/ydb-platform/ydb/blob/9335b61d3316afbf9508d435ad2fff4fed6b6b2c/ydb/public/api/protos/ydb_value.proto#L163

Here high_128 is not optional.

**Review by ijon — APPROVED** [review]
