### PR TITLE
Fix cross join with list iterator.

### LINKED ISSUE #4587: YQL: Cross join results depends on input order
The attached request has cross join over table and window function. Different input order leads to different result. Seems window function doesn't work correctly.

P.S. Roman asked to assign this ticket to you as the main professional in this sphere.

[test1_bad_sql.txt](https://github.com/ydb-platform/ydb/files/15332393/test1_bad_sql.txt)
[test2_good_sql.txt](https://github.com/ydb-platform/ydb/files/15332394/test2_good_sql.txt)
[trace_opt_1_bad.txt](https://github.com/ydb-platform/ydb/files/15332395/trace_opt_1_bad.txt)
[trace_opt_2_good.txt](https://github.com/ydb-platform/ydb/files/15332396/trace_opt_2_good.txt)

### PR DESCRIPTION
**Pull request by Tony-Romanov**

### CODE REVIEW

File: ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp [hunk 1]
```diff
@@ -565,6 +565,33 @@ TExprNode::TPtr ExpandEquiJoinImpl(const TExprNode& node, TExprContext& ctx) {
...
+                switch (children.size()) {
+                    case 1U: {
+                        children.emplace_back(ctx.NewCallable(iter->Pos(), "DependsOn", {upperArg}));
+                        break;
+                    }
+                    case 2U: {
+                        auto deps = children.back()->ChildrenList();
+                        deps.emplace_back(upperArg);
+                        children.back() = ctx.ChangeChildren(*children.back(), std::move(deps));
+;                       break;
```
Comment (mxkovalev) [inline ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp]: redundant `;`

**Comment by mxkovalev** [comment]
I've rerun two attached scripts to the issue and doesn't get `size(cross_join(a, b)) == size(cross_join(b, a))`

**Comment by mxkovalev** [comment]
When I rerun an example from the issue, data generated from `cross_join(a, b)` and `cross_join(b, a)` are very different.

**Review by mxkovalev — APPROVED** [review]
