### PR TITLE
Make timeout on reestablishing sessions in BSQueue longer on high load

### LINKED ISSUE #17717: Avoid request storm in BS_QUEUE_ACTOR after network recovery
When the network briefly goes down, after the link is restored, the interconnect cannot re-establish connections, consuming 6 cores.

The log shows the following error:

```
DNS (Mar 2 09:37:24 vla04 NBS_SERVER[2592644]: 2025-03-02T07:37:24.975239Z :INTERCONNECT_NETWORK NOTICE: [65036 <-> 785] network-related error occurred on handshake: outgoing handshake Peer# [vla04-.net](https://vla04-.net/)(<unknown>) DNS resolve timed out)
```

The DNS resolves the address, but the problem arises because about a million `BS_QUEUE_ACTOR` actors with a 1-second timeout are trying to establish a connection, and due to the flood of requests, they all fail to fit within the timeout.

Image

KIKIMR-22823

### PR DESCRIPTION
**Pull request by serbel324**
### Changelog entry 

Increase timeout on BS_QUEUE reestablishing session when many actors try to reconnect simultaneously

### Changelog category 

* Improvement

### CODE REVIEW

File: ydb/core/blobstorage/backpressure/load_based_timeout.h [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    }
+
+private:
+    TDuration MinimumTimeout;
+    TDuration TimePerRequestInFlight;
+    static std::atomic<ui32> RequestsInFlight;
+    bool ActiveRequest;
+};
+
+std::atomic<ui32> TLoadBasedTimeoutManager::RequestsInFlight = 0;
```
Comment (alexvru) [inline ydb/core/blobstorage/backpressure/load_based_timeout.h:41]: Global variable in header?

**Review by alexvru — CHANGES_REQUESTED** [review]

**Review by alexvru — APPROVED** [review]
