### PR TITLE
YQL-18007: Fix implicit casts in PgLike

### LINKED ISSUE #2366: No implicit casts from name to pgtext
```
SELECT t.oid, t.typname AS name
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_type e ON e.oid=t.typelem
LEFT OUTER JOIN pg_catalog.pg_class ct ON ct.oid=t.typrelid AND ct.relkind <> 'c'
LEFT OUTER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = t.typnamespace
WHERE t.typtype != 'd' AND t.typname NOT LIKE E'\_%' AND t.typnamespace = 1::oid
AND ct.oid is NULL
ORDER BY t.typname
```

gives
```
Expected pg text, but got name
```

### PR DESCRIPTION
**Pull request by marsaly79**
### Changelog entry 

...

### Changelog category 

* Bugfix 

### Additional information

Fixes #2366

### CODE REVIEW

File: ydb/library/yql/core/type_ann/type_ann_pg.cpp [hunk 1]
```diff
@@ -4908,8 +4908,21 @@ IGraphTransformer::TStatus PgLikeWrapper(const TExprNode::TPtr& input, TExprNode
             continue;
         }
 
+        auto canCast = [] (const ui32 sourceType, const ui32 targetType) {
```
Comment (vitstn) [inline ydb/library/yql/core/type_ann/type_ann_pg.cpp:4911]: It looks like a generic function. Please extract or reuse an existing one

**Review by vitstn — APPROVED** [review]
