### PR TITLE
YQ-3561 supported in memory cp storage

### LINKED ISSUE #14903: when shard replies "MaxTxInFly was exceeded" KQP returns Unavailable
InternalError: UNAVAILABLE DEFAULT_ERROR: { <main>: Error: Too many retries for shard <> subissue: { <main>: Error: Request 0 rejected, MaxTxInFly was exceeded

### PR DESCRIPTION
**Pull request by GrigoriyPA**
### Changelog entry 

Supported in memory cp storage

### Changelog category 

* Improvement

### Description for reviewers

### CODE REVIEW

File: ydb/core/fq/libs/control_plane_storage/in_memory_control_plane_storage.cpp [hunk 1]
```diff
@@ -343,50 +773,242 @@ class TInMemoryControlPlaneStorageActor : public NActors::TActor<TInMemoryContro
...
         }
+        return true;
+    }
 
-        if (request.ByteSize() > static_cast<int>(Config.Proto.GetMaxRequestSize())) {
-            issues.AddIssue(MakeErrorIssue(TIssuesIds::BAD_REQUEST, "Request size exceeded " + ToString(request.ByteSize()) + " out of " + ToString(Config.Proto.GetMaxRequestSize()) + " bytes"));
+    template <typename TTable>
+    static ui64 GetNumberEntitiesByScope(const TTable& table, const TString& scope) {
+        ui64 result = 0;
+        for (const auto& [key, _] : table.Values) {
```
Comment (yumkam) [inline ydb/core/fq/libs/control_plane_storage/in_memory_control_plane_storage.cpp:840]: nit: `.lower_bound()`

**Review by kardymonds — APPROVED** [review]
