### PR TITLE
Fix excessive read latency during and after shard splits

### LINKED ISSUE #11036: DataShard: read actors retry TEvRead to shards long after they finished splitting
Looks like DataShard currently replies with a very generic error:

```
    if (!IsStateNewReadAllowed()) {
        replyWithError(
            Ydb::StatusIds::OVERLOADED,
            TStringBuilder() << "Shard " << TabletID() << " is splitting/merging"
                << " (node# " << SelfId().NodeId() << " state# " << DatashardStateName(State) << ")");
        return;
    }
```

Which causes ReadActor (LookupActor?) to keep retrying with an expotential backoff without resolving new partitioning. I've seen this causing 3+ seconds latency (due to expotential backoff) until it finally requests the new shard.

### PR DESCRIPTION
**Pull request by snaury**
### Changelog entry 

Fixed excessive read latency during and after some shard splits.

### Changelog category 

* Bugfix 

### Additional information

It was observed that reads sometimes take seconds during frequent shard splits. Turns out shards replied with an `OVERLOADED` status even after split has already finished, which caused KQP to retry reads repeatedly with an exponential backoff, until eventually a guard condition (after multiple seconds) would cause read actor to finally re-resolve the table again. A correct `NOT_FOUND` status (which indicates the table no longer exists) fixes this problem.

Fixes #11036.

### CODE REVIEW

File: ydb/core/tx/datashard/datashard_ut_read_iterator.cpp [hunk 1]
```diff
@@ -4719,4 +4719,70 @@ Y_UNIT_TEST_SUITE(DataShardReadIteratorConsistency) {
...
+        runtime.SimulateSleep(TDuration::MilliSeconds(1));
+
+        auto readStartTs = runtime.GetCurrentTime();
+        blockedReads.Unblock();
+        blockedReads.Stop();
+        auto readResponse = runtime.WaitFuture(std::move(readFuture));
+        UNIT_ASSERT_VALUES_EQUAL(readResponse.operation().status(), Ydb::StatusIds::SUCCESS);
+        auto readLatency = runtime.GetCurrentTime() - readStartTs;
+        Cerr << "... read latency was " << readLatency << Endl;
+        UNIT_ASSERT_C(readLatency < TDuration::MilliSeconds(100),
```
Comment (azevaykin) [inline ydb/core/tx/datashard/datashard_ut_read_iterator.cpp:4782]: Is that all right under sanitizer?

File: ydb/core/tx/datashard/datashard__read_iterator.cpp [hunk 2]
```diff
@@ -2657,6 +2657,16 @@ void TDataShard::Handle(TEvDataShard::TEvRead::TPtr& ev, const TActorContext& ct
         return;
     }
 
+    if (State == TShardState::PreOffline ||
+        State == TShardState::Offline)
+    {
+        replyWithError(
+            Ydb::StatusIds::NOT_FOUND,
```
Comment (azevaykin) [inline ydb/core/tx/datashard/datashard__read_iterator.cpp:2664]: Don't you want to catch is the test  `EvReadResult` and check status 'NOT_FOUND' ?

File: ydb/core/tx/datashard/datashard_ut_read_iterator.cpp (hunk 1 above)
Comment (snaury) [reply ydb/core/tx/datashard/datashard_ut_read_iterator.cpp:4782]: This is simulated time, it shouldn't change regardless of how slow this runs.

File: ydb/core/tx/datashard/datashard__read_iterator.cpp (hunk 2 above)
Comment (snaury) [reply ydb/core/tx/datashard/datashard__read_iterator.cpp:2664]: Why? I want to observe and test the effect (high latency), not some implementation detail.

**Review by azevaykin — APPROVED** [review]
