### PR TITLE
Fix data race on Checksumming field in TGroupSessions

### LINKED ISSUE #26059: TSAN: data race /-S/ydb/core/blobstorage/dsproxy/group_sessions.cpp:131:35 @ TGroupSessions::QueueConnectUpdate
[Nemesis run with TSAN](https://nda.ya.ru/t/bqky03hn7Kes2n)

Problematic stress-utils:

- ctas
- show create
- simple queue [row]
- key-value [row]
- transfer [local]

Tsan output:
```
WARNING: ThreadSanitizer: data race (pid=397120)
  Read of size 1 at 0x729c0007840b by thread T133:
    #0 has_value /-S/contrib/libs/cxxsupp/libcxx/include/optional:356:82 (kikimr+0x2b7bb4c0) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #1 value_or<bool> /-S/contrib/libs/cxxsupp/libcxx/include/optional:855:18 (kikimr+0x2b7bb4c0)
    #2 NKikimr::TGroupQueues::ChecksumExpected(NKikimr::TBlobStorageGroupInfo::TTopology const&, NKikimr::TVDiskID, NKikimrBlobStorage::EVDiskQueueId) /-S/ydb/core/blobstorage/dsproxy/group_sessions.h:193:18 (kikimr+0x2b7bb4c0)
    #3 NKikimr::TPutImpl::GeneratePutRequests() /-S/ydb/core/blobstorage/dsproxy/dsproxy_put_impl.h:242:63 (kikimr+0x2b82eb13) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #4 NKikimr::TBlobStorageGroupPutRequest::Action(bool) /-S/ydb/core/blobstorage/dsproxy/dsproxy_put.cpp:125:31 (kikimr+0x2b82b41b) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #5 NKikimr::TBlobStorageGroupPutRequest::ResumeBootstrap() /-S/ydb/core/blobstorage/dsproxy/dsproxy_put.cpp:769:13 (kikimr+0x2b82195a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #6 NKikimr::TBlobStorageGroupPutRequest::Bootstrap() /-S/ydb/core/blobstorage/dsproxy/dsproxy_put.cpp:687:9 (kikimr+0x2b819b41) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #7 BootstrapImpl /-S/ydb/core/blobstorage/dsproxy/dsproxy_request.cpp:702:13 (kikimr+0x2b74c113) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #8 NKikimr::TBlobStorageGroupRequestActor::InitialStateFunc(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/core/blobstorage/dsproxy/dsproxy_request.cpp:695:5 (kikimr+0x2b74c113)
    #9 NActors::IActor::Receive(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/library/actors/core/actor.cpp:406:17 (kikimr+0x1a3dd16a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #10 NActors::TExecutorThread::Execute(NActors::TMailbox*, bool) /-S/ydb/library/actors/core/executor_thread.cpp:268:28 (kikimr+0x1a4460af) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #11 NActors::TExecutorThread::ProcessExecutorPool()::$_0::operator()(NActors::TMailbox*, bool) const /-S/ydb/library/actors/core/executor_thread.cpp:458:39 (kikimr+0x1a44bd68) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #12 NActors::TExecutorThread::ProcessExecutorPool() /-S/ydb/library/actors/core/executor_thread.cpp:510:13 (kikimr+0x1a44b71c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #13 NActors::TExecutorThread::ThreadProc() /-S/ydb/library/actors/core/executor_thread.cpp:536:9 (kikimr+0x1a44ca82) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #14 void* (anonymous namespace)::ThreadProcWrapper<ISimpleThread>(void*) /-S/util/system/thread.cpp:386:45 (kikimr+0x18e70582) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #15 (anonymous namespace)::TPosixThread::ThreadProxy(void*) /-S/util/system/thread.cpp:245:20 (kikimr+0x18e73e70) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
  Previous write of size 4 at 0x729c00078408 by thread T142:
    #0 NKikimr::TGroupSessions::QueueConnectUpdate(unsigned int, NKikimrBlobStorage::EVDiskQueueId, bool, bool, bool, std::__y1::shared_ptr<NKikimr::TCostModel const>, NKikimr::TBlobStorageGroupInfo::TTopology const&) /-S/ydb/core/blobstorage/dsproxy/group_sessions.cpp:131:35 (kikimr+0x2b67f7cd) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #1 NKikimr::TBlobStorageGroupProxy::Handle(TAutoPtr<NActors::TEventHandle<NKikimr::TEvProxyQueueState>, TDelete>&) /-S/ydb/core/blobstorage/dsproxy/dsproxy_state.cpp:238:19 (kikimr+0x2b66335e) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #2 NKikimr::TBlobStorageGroupProxy::StateCommon(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/core/blobstorage/dsproxy/dsproxy_impl.h:373:5 (kikimr+0x2b67a2f9) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #3 NKikimr::TBlobStorageGroupProxy::StateWork(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/core/blobstorage/dsproxy/dsproxy_impl.h:440:29 (kikimr+0x2b65e754) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #4 NActors::IActor::Receive(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/library/actors/core/actor.cpp:406:17 (kikimr+0x1a3dd16a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #5 NActors::TExecutorThread::Execute(NActors::TMailbox*, bool) /-S/ydb/library/actors/core/executor_thread.cpp:268:28 (kikimr+0x1a4460af) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #6 NActors::TExecutorThread::ProcessExecutorPool()::$_0::operator()(NActors::TMailbox*, bool) const /-S/ydb/library/actors/core/executor_thread.cpp:458:39 (kikimr+0x1a44bd68) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #7 NActors::TExecutorThread::ProcessExecutorPool() /-S/ydb/library/actors/core/executor_thread.cpp:510:13 (kikimr+0x1a44b71c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #8 NActors::TExecutorThread::ThreadProc() /-S/ydb/library/actors/core/executor_thread.cpp:536:9 (kikimr+0x1a44ca82) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #9 void* (anonymous namespace)::ThreadProcWrapper<ISimpleThread>(void*) /-S/util/system/thread.cpp:386:45 (kikimr+0x18e70582) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #10 (anonymous namespace)::TPosixThread::ThreadProxy(void*) /-S/util/system/thread.cpp:245:20 (kikimr+0x18e73e70) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
  Location is heap block of size 13792 at 0x729c00077000 allocated by thread T135:
    #0 operator new(unsigned long) /place/sandbox-data/tasks/1/1/3398177511/ydb/contrib/libs/clang20-rt/lib/tsan/rtl/tsan_new_delete.cpp:64:3 (kikimr+0x18ca0f82) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #1 MakeIntrusive<NKikimr::TGroupQueues, TDefaultIntrusivePtrOps<NKikimr::TGroupQueues>, const NKikimr::TBlobStorageGroupInfo::TTopology &> /-S/util/generic/ptr.h:834:12 (kikimr+0x2b67de3c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #2 NKikimr::TGroupSessions::TGroupSessions(TIntrusivePtr<NKikimr::TBlobStorageGroupInfo, TDefaultIntrusivePtrOps<NKikimr::TBlobStorageGroupInfo>> const&, TIntrusivePtr<NKikimr::TBSProxyContext, TDefaultIntrusivePtrOps<NKikimr::TBSProxyContext>> const&, NActors::TActorId const&, NActors::TActorId const&, bool) /-S/ydb/core/blobstorage/dsproxy/group_sessions.cpp:32:19 (kikimr+0x2b67de3c)
    #3 MakeIntrusive<NKikimr::TGroupSessions, TDefaultIntrusivePtrOps<NKikimr::TGroupSessions>, TIntrusivePtr<NKikimr::TBlobStorageGroupInfo, TDefaultIntrusivePtrOps<NKikimr::TBlobStorageGroupInfo> > &, TIntrusivePtr<NKikimr::TBSProxyContext, TDefaultIntrusivePtrOps<NKikimr::TBSProxyContext> > &, NActors::TActorId &, NActors::TActorIdentity, bool &> /-S/util/generic/ptr.h:834:16 (kikimr+0x2b65ff59) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #4 NKikimr::TBlobStorageGroupProxy::ApplyGroupInfo(TIntrusivePtr<NKikimr::TBlobStorageGroupInfo, TDefaultIntrusivePtrOps<NKikimr::TBlobStorageGroupInfo>>&&, TIntrusivePtr<NKikimr::TNodeLayoutInfo, TDefaultIntrusivePtrOps<NKikimr::TNodeLayoutInfo>>, TIntrusivePtr<NKikimr::TStoragePoolCounters, TDefaultIntrusivePtrOps<NKikimr::TStoragePoolCounters>>&&) /-S/ydb/core/blobstorage/dsproxy/dsproxy_state.cpp:170:28 (kikimr+0x2b65ff59)
    #5 Handle /-S/ydb/core/blobstorage/dsproxy/dsproxy_state.cpp:92:9 (kikimr+0x2b67a1b8) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #6 NKikimr::TBlobStorageGroupProxy::StateCommon(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/core/blobstorage/dsproxy/dsproxy_impl.h:373:5 (kikimr+0x2b67a1b8)
    #7 NKikimr::TBlobStorageGroupProxy::StateUnconfigured(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/core/blobstorage/dsproxy/dsproxy_impl.h:411:29 (kikimr+0x2b65d66a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #8 NActors::IActor::Receive(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/ydb/library/actors/core/actor.cpp:406:17 (kikimr+0x1a3dd16a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #9 NActors::TExecutorThread::Execute(NActors::TMailbox*, bool) /-S/ydb/library/actors/core/executor_thread.cpp:268:28 (kikimr+0x1a4460af) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #10 NActors::TExecutorThread::ProcessExecutorPool()::$_0::operator()(NActors::TMailbox*, bool) const /-S/ydb/library/actors/core/executor_thread.cpp:458:39 (kikimr+0x1a44bd68) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #11 NActors::TExecutorThread::ProcessExecutorPool() /-S/ydb/library/actors/core/executor_thread.cpp:510:13 (kikimr+0x1a44b71c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #12 NActors::TExecutorThread::ThreadProc() /-S/ydb/library/actors/core/executor_thread.cpp:536:9 (kikimr+0x1a44ca82) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #13 void* (anonymous namespace)::ThreadProcWrapper<ISimpleThread>(void*) /-S/util/system/thread.cpp:386:45 (kikimr+0x18e70582) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #14 (anonymous namespace)::TPosixThread::ThreadProxy(void*) /-S/util/system/thread.cpp:245:20 (kikimr+0x18e73e70) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
  Thread T133 'kikimr.System' (tid=397657, running) created by main thread at:
    #0 pthread_create /place/sandbox-data/tasks/1/1/3398177511/ydb/contrib/libs/clang20-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1041:3 (kikimr+0x18c1ae0a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #1 Start /-S/util/system/thread.cpp:230:27 (kikimr+0x18e6b605) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #2 TThread::Start() /-S/util/system/thread.cpp:315:34 (kikimr+0x18e6b605)
    #3 NActors::TBasicExecutorPool::Start() /-S/ydb/library/actors/core/executor_pool_basic.cpp:568:32 (kikimr+0x1a426ee8) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #4 NActors::TCpuManager::Start() /-S/ydb/library/actors/core/cpu_manager.cpp:141:32 (kikimr+0x1a3f1893) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #5 NActors::TActorSystem::Start() /-S/ydb/library/actors/core/actorsystem.cpp:413:21 (kikimr+0x1a3ea6d6) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #6 NKikimr::TKikimrRunner::KikimrStart() /place/sandbox-data/tasks/6/2/3415336526/ydb/ydb/core/driver_lib/run/run.cpp:1986:22 (kikimr+0x2c96de9c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #7 NKikimr::MainRun(NKikimr::TKikimrRunConfig const&, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:46:17 (kikimr+0x2b0ccc79) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #8 NKikimr::NDriverClient::TClientCommandServer::Run(NYdb::NConsoleClient::TClientCommand::TConfig&) /-S/ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp:50:12 (kikimr+0x2c8995b1) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #9 NYdb::NConsoleClient::TClientCommand::ValidateAndRun(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:315:16 (kikimr+0x2b11669a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #10 NYdb::NConsoleClient::TClientCommandTree::Run(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:512:33 (kikimr+0x2b1191ab) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #11 NYdb::NConsoleClient::TClientCommand::ValidateAndRun(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:315:16 (kikimr+0x2b11669a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #12 NYdb::NConsoleClient::TClientCommand::Process(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:257:16 (kikimr+0x2b11586d) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #13 NKikimr::NDriverClient::NewClient(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/cli_utils/cli_cmds_root.cpp:77:26 (kikimr+0x2b10dd3c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #14 NKikimr::Main(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:151:20 (kikimr+0x2b0d10a4) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #15 ParameterizedMain(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:201:16 (kikimr+0x2b0d2853) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #16 main /-S/ydb/apps/ydbd/main.cpp:31:12 (kikimr+0x18bf496c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
  Thread T142 'kikimr.System' (tid=397666, running) created by main thread at:
    #0 pthread_create /place/sandbox-data/tasks/1/1/3398177511/ydb/contrib/libs/clang20-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1041:3 (kikimr+0x18c1ae0a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #1 Start /-S/util/system/thread.cpp:230:27 (kikimr+0x18e6b605) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #2 TThread::Start() /-S/util/system/thread.cpp:315:34 (kikimr+0x18e6b605)
    #3 NActors::TBasicExecutorPool::Start() /-S/ydb/library/actors/core/executor_pool_basic.cpp:568:32 (kikimr+0x1a426ee8) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #4 NActors::TCpuManager::Start() /-S/ydb/library/actors/core/cpu_manager.cpp:141:32 (kikimr+0x1a3f1893) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #5 NActors::TActorSystem::Start() /-S/ydb/library/actors/core/actorsystem.cpp:413:21 (kikimr+0x1a3ea6d6) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #6 NKikimr::TKikimrRunner::KikimrStart() /place/sandbox-data/tasks/6/2/3415336526/ydb/ydb/core/driver_lib/run/run.cpp:1986:22 (kikimr+0x2c96de9c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #7 NKikimr::MainRun(NKikimr::TKikimrRunConfig const&, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:46:17 (kikimr+0x2b0ccc79) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #8 NKikimr::NDriverClient::TClientCommandServer::Run(NYdb::NConsoleClient::TClientCommand::TConfig&) /-S/ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp:50:12 (kikimr+0x2c8995b1) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #9 NYdb::NConsoleClient::TClientCommand::ValidateAndRun(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:315:16 (kikimr+0x2b11669a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #10 NYdb::NConsoleClient::TClientCommandTree::Run(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:512:33 (kikimr+0x2b1191ab) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #11 NYdb::NConsoleClient::TClientCommand::ValidateAndRun(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:315:16 (kikimr+0x2b11669a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #12 NYdb::NConsoleClient::TClientCommand::Process(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:257:16 (kikimr+0x2b11586d) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #13 NKikimr::NDriverClient::NewClient(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/cli_utils/cli_cmds_root.cpp:77:26 (kikimr+0x2b10dd3c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #14 NKikimr::Main(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:151:20 (kikimr+0x2b0d10a4) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #15 ParameterizedMain(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:201:16 (kikimr+0x2b0d2853) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #16 main /-S/ydb/apps/ydbd/main.cpp:31:12 (kikimr+0x18bf496c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
  Thread T135 'kikimr.System' (tid=397659, running) created by main thread at:
    #0 pthread_create /place/sandbox-data/tasks/1/1/3398177511/ydb/contrib/libs/clang20-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1041:3 (kikimr+0x18c1ae0a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #1 Start /-S/util/system/thread.cpp:230:27 (kikimr+0x18e6b605) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #2 TThread::Start() /-S/util/system/thread.cpp:315:34 (kikimr+0x18e6b605)
    #3 NActors::TBasicExecutorPool::Start() /-S/ydb/library/actors/core/executor_pool_basic.cpp:568:32 (kikimr+0x1a426ee8) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #4 NActors::TCpuManager::Start() /-S/ydb/library/actors/core/cpu_manager.cpp:141:32 (kikimr+0x1a3f1893) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #5 NActors::TActorSystem::Start() /-S/ydb/library/actors/core/actorsystem.cpp:413:21 (kikimr+0x1a3ea6d6) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #6 NKikimr::TKikimrRunner::KikimrStart() /place/sandbox-data/tasks/6/2/3415336526/ydb/ydb/core/driver_lib/run/run.cpp:1986:22 (kikimr+0x2c96de9c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #7 NKikimr::MainRun(NKikimr::TKikimrRunConfig const&, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:46:17 (kikimr+0x2b0ccc79) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #8 NKikimr::NDriverClient::TClientCommandServer::Run(NYdb::NConsoleClient::TClientCommand::TConfig&) /-S/ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp:50:12 (kikimr+0x2c8995b1) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #9 NYdb::NConsoleClient::TClientCommand::ValidateAndRun(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:315:16 (kikimr+0x2b11669a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #10 NYdb::NConsoleClient::TClientCommandTree::Run(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:512:33 (kikimr+0x2b1191ab) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #11 NYdb::NConsoleClient::TClientCommand::ValidateAndRun(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:315:16 (kikimr+0x2b11669a) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #12 NYdb::NConsoleClient::TClientCommand::Process(NYdb::NConsoleClient::TClientCommand::TConfig&) /place/sandbox-data/tasks/1/1/3398177511/ydb/ydb/public/lib/ydb_cli/common/command.cpp:257:16 (kikimr+0x2b11586d) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #13 NKikimr::NDriverClient::NewClient(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/cli_utils/cli_cmds_root.cpp:77:26 (kikimr+0x2b10dd3c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #14 NKikimr::Main(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:151:20 (kikimr+0x2b0d10a4) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #15 ParameterizedMain(int, char**, std::__y1::shared_ptr<NKikimr::TModuleFactories>) /-S/ydb/core/driver_lib/run/main.cpp:201:16 (kikimr+0x2b0d2853) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
    #16 main /-S/ydb/apps/ydbd/main.cpp:31:12 (kikimr+0x18bf496c) (BuildId: f3b9a5d9d249e285ac07f31ff2ee4ee81d1dc18b)
SUMMARY: ThreadSanitizer: data race /-S/contrib/libs/cxxsupp/libcxx/include/optional:356:82 in has_value
==================

```

### PR DESCRIPTION
**Pull request by serbel324**
### Changelog entry 

Fixes https://github.com/ydb-platform/ydb/issues/26059

### Changelog category 

* Bugfix

### Description for reviewers 

Checksumming field may be accessed from different threads, so we make it atomic.

### CODE REVIEW

File: ydb/core/blobstorage/dsproxy/group_sessions.h [hunk 1]
```diff
@@ -22,7 +22,7 @@ namespace NKikimr {
                     TActorId ActorId;
                     TIntrusivePtr<NBackpressure::TFlowRecord> FlowRecord;
                     std::optional<bool> ExtraBlockChecksSupport;
-                    std::optional<bool> Checksumming;
+                    std::atomic<bool> Checksumming;
```
Comment (uzhastik) [inline ydb/core/blobstorage/dsproxy/group_sessions.h]: рекомендую проинициализировать

**Review by kruall — APPROVED** [review]
