### PR TITLE
healthcheck: fix handling of response from a disconnected node

### LINKED ISSUE #22390: health check: false-positive unresponsive tablets during cluster updates
During cloud cluster updates, HC API reports lots of tablets as unresponsive. Tracing shows that HC replies without waiting for those tablets to respond:

Image

Apparently this is caused by HC first receiving NodeDisconnected, then the actual response from the node, which leads to a double-decrement of the requests-in-flight counter

Image

This behavior has been observed since January,  which means it was likely introduced in https://github.com/ydb-platform/ydb/commit/462f21608bcc3fc71b6660065ec05f5b769740d4 

Image

### PR DESCRIPTION
**Pull request by vporyadke**
### Changelog entry 

fix false-positive unresponsive tablet issues in healthcheck during restarts https://github.com/ydb-platform/ydb/issues/22390

### Changelog category 

* Bugfix 

### Description for reviewers 

...

### CODE REVIEW

**Review by adameat — APPROVED** [review]

File: ydb/core/health_check/health_check_ut.cpp [hunk 1]
```diff
@@ -2722,6 +2723,38 @@ Y_UNIT_TEST_SUITE(THealthCheckTest) {
...
+        TClient client(settings);
+        TTestActorRuntime& runtime = *server.GetRuntime();
+
+        TActorId sender = runtime.AllocateEdgeActor();
+        TAutoPtr<IEventHandle> handle;
+
+        auto observer = runtime.AddObserver<TEvWhiteboard::TEvSystemStateResponse>([&](auto&& ev) {
+            auto actor = ev->Recipient;
+            auto nodeId = ev->Sender.NodeId();
+            Cerr << "Observing " << ev->ToString() << Endl;
```
Comment (stanislav-shchetinin) [inline ydb/core/health_check/health_check_ut.cpp:2745]: Забыл убрать или так и задумано?

Comment (vporyadke) [reply ydb/core/health_check/health_check_ut.cpp:2745]: Лишний вывод в тесте не помешает =)

**Review by stanislav-shchetinin — APPROVED** [review]
