### PR TITLE
Bridge Mode in SB: gracefully continue sync request execution in case of concurrent reconfiguration

### LINKED ISSUE #20645: Bridge Mode in SB: gracefully continue sync request execution in case of config change
Reconfiguration stress tests are failing because of this:

https://wiki.yandex-team.ru/users/deminds/tmp-scheme-board-stress-test-debugging/

### PR DESCRIPTION
**Pull request by jepett0**
### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

Epic:
- https://github.com/ydb-platform/ydb/issues/19748

Issue:
- https://github.com/ydb-platform/ydb/issues/20645

### CODE REVIEW

File: ydb/core/tx/scheme_board/subscriber.cpp [hunk 1]
```diff
@@ -1040,6 +1040,10 @@ class TSubscriber: public TMonitorableActor<TDerived> {
                 this->Send(proxy, new TEvents::TEvPoisonPill());
             }
         }
+        if (CurrentSyncRequest) {
+            this->Send(Owner, new NInternalEvents::TEvSyncResponse(Path, true), 0, CurrentSyncRequest);
+            CurrentSyncRequest = 0;
+        }
```
Comment (CyberROFL) [inline ydb/core/tx/scheme_board/subscriber.cpp]:
```suggestion

        if (CurrentSyncRequest) {
            this->Send(Owner, new NInternalEvents::TEvSyncResponse(Path, true), 0, CurrentSyncRequest);
            CurrentSyncRequest = 0;
        }

```
Можно так, чтобы визуально отделить.

**Review by CyberROFL — DISMISSED** [review]

File: ydb/core/tx/scheme_board/subscriber.cpp (hunk 1 above)
Comment (jepett0) [reply ydb/core/tx/scheme_board/subscriber.cpp]: Отделил в обновлённой версии

**Review by CyberROFL — APPROVED** [review]
