### PR TITLE
Fix acceleration in mirror-3-dc groups

### LINKED ISSUE #7840: Fix Acceleration behaviour on disabled tests

### PR DESCRIPTION
**Pull request by serbel324**
- **Intermediate**
- **Fix acceleration in mirror-3-dc**

### Changelog entry 

Fixed Acceleration in mirror-3-dc and UT environment

### Changelog category 

* Bugfix

### Additional information

...

### CODE REVIEW

File: ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h [hunk 1]
```diff
@@ -236,4 +235,45 @@ inline bool RestoreWholeFromMirror(TBlobState& state) {
     return !state.Whole.NotHere();
 }
 
+inline ui32 MakeSlowSubgroupDiskMaskForTwoSlowest(TBlobState &state, const TBlobStorageGroupInfo &info,
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h:238]: Are you sure it should be inline?

File: ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h [hunk 2]
```diff
@@ -166,7 +165,7 @@ class IStrategy {
 
 struct TBlackboard {
     enum EAccelerationMode {
-        AccelerationModeSkipOneSlowest,
+        AccelerationModeSkipTwoSlowest,
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h:168]: And what if we want to skip one slowest?

File: ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h [hunk 3]
```diff
@@ -236,4 +235,45 @@ inline bool RestoreWholeFromMirror(TBlobState& state) {
...
+    // Check if two slowest disks are exceptionally slow, or just not very fast
+    ui32 slowDiskSubgroupMask = 0;
+
+    ui64 slowThreshold = worstDisks[2].PredictedNs * accelerationParams.SlowDiskThreshold;
+    if (slowThreshold == 0) {
+        // invalid or non-initialized predicted ns, consider all disks not slow
+        return 0;
+    }
+
+    for (size_t idx = 0; idx < state.Disks.size(); ++idx) {
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h:261]: Ranged for here?

File: ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h [hunk 4]
```diff
@@ -236,4 +235,45 @@ inline bool RestoreWholeFromMirror(TBlobState& state) {
...
+            ui32 orderNumber = worstDisks[idx].DiskIdx;
+            slowDiskSubgroupMask |= 1 << orderNumber;
+            state.Disks[orderNumber].IsSlow = true;
+            if (slowIdxs) {
+                slowIdxs->push_back(orderNumber);
+            }
+        }
+    }
+
+    return slowDiskSubgroupMask;
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h:276]: Honestly I don't like two parallel sets of slow disks -- IsSlow flag and this mask. They will eventually go out of sync sometimes after a code change.

File: ydb/core/blobstorage/dsproxy/dsproxy_get_impl.cpp [hunk 5]
```diff
@@ -154,7 +154,7 @@ ui64 TGetImpl::GetTimeToAccelerateNs(TLogContext &logCtx, NKikimrBlobStorage::EV
                 *Info, *Blackboard.GroupQueues, queueId, &worstDisks,
                 AccelerationParams.PredictedDelayMultiplier);
     }
-    return worstDisks[std::min(3u, (ui32)worstDisks.size() - 1)].PredictedNs;
+    return worstDisks[std::min(2u, (ui32)worstDisks.size() - 1)].PredictedNs;
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_get_impl.cpp:157]: No numeric constants except for 0 and 1, please :)

File: ydb/core/blobstorage/dsproxy/dsproxy_strategy_accelerate_put_m3dc.h [hunk 6]
```diff
@@ -45,7 +45,7 @@ class TAcceleratePut3dcStrategy : public TStrategyBase {
             }
         }
         if (badDiskMask > 0) {
-            // Mark the 'bad' disk as the single slow disk
+            // Mark all the slow disks
             for (size_t diskIdx = 0; diskIdx < state.Disks.size(); ++diskIdx) {
                 state.Disks[diskIdx].IsSlow = badDiskMask & (1 << diskIdx);
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_strategy_accelerate_put_m3dc.h:50]: Possible out of sync goes here.

File: ydb/core/blobstorage/dsproxy/dsproxy_strategy_base.cpp [hunk 7]
```diff
@@ -363,10 +363,11 @@ void TStrategyBase::Evaluate3dcSituation(const TBlobState &state,
     }
 }
 
-void TStrategyBase::Prepare3dcPartPlacement(const TBlobState &state,
+bool TStrategyBase::Prepare3dcPartPlacement(const TBlobState &state,
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_strategy_base.cpp:366]: Return fullPlacement through out parameter. Otherwise there is a mixup of return values and return parameters -- it is not obvious what this function returns (based on its name).

File: ydb/core/blobstorage/dsproxy/dsproxy_strategy_base.cpp [hunk 8]
```diff
@@ -385,40 +386,19 @@ void TStrategyBase::Prepare3dcPartPlacement(const TBlobState &state,
...
-            for (size_t diskIdx = 0; diskIdx < state.Disks.size(); ++diskIdx) {
-                state.Disks[diskIdx].IsSlow = false;
-            }
-            if (slowDiskSubgroupMask > 0) {
-                state.Disks[worstDisks[0].DiskIdx].IsSlow = true;
-            }
-
-            return slowDiskSubgroupMask;
+        case TBlackboard::AccelerationModeSkipTwoSlowest: {
+            return MakeSlowSubgroupDiskMaskForTwoSlowest(state, info, blackboard, isPut, accelerationParams);
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_strategy_base.cpp:401]: I suggest you making this code a bit more universal -- mark slowest N disks. Instead of patching the code every time.

File: ydb/core/blobstorage/dsproxy/dsproxy_strategy_get_m3dc_basic.h [hunk 9]
```diff
@@ -71,30 +71,11 @@ namespace NKikimr {
             // issue request for a specific disk; returns true if the request was issued and not yet completed, otherwise
             // false
 
-            if (info.GetTotalVDisksNum() > 1) {
+            if (info.GetTotalVDisksNum() >= 3) {
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_strategy_get_m3dc_basic.h:74]: This is mirror-3-dc-specific strategy, TotalVDisksNum can't be less than 9.

**Review by alexvru — CHANGES_REQUESTED** [review]

File: ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp [hunk 10]
```diff
@@ -542,4 +542,35 @@ void TBlackboard::InvalidatePartStates(ui32 orderNumber) {
...
+    }
+
+    ui32 maxNumSlow = accelerationParams.MaxNumOfSlowDisks;
+    if (Info->GetTotalVDisksNum() <= maxNumSlow) {
+        // all disks cannot be slow
+        return;
+    }
+    
+    TDiskDelayPredictions worstDisks;
+    state.GetWorstPredictedDelaysNs(*Info, *GroupQueues,
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp:558]: Aaand this code does partial sort for only 3 disks, right? So this won't work in general case.

File: ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp [hunk 11]
```diff
@@ -542,4 +542,35 @@ void TBlackboard::InvalidatePartStates(ui32 orderNumber) {
...
+            (isPut ? HandleClassToQueueId(PutHandleClass) : HandleClassToQueueId(GetHandleClass)),
+            &worstDisks, accelerationParams.PredictedDelayMultiplier);
+
+    ui64 slowThreshold = worstDisks[maxNumSlow].PredictedNs * accelerationParams.SlowDiskThreshold;
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp:562]: In case of 2 slow disks this would be the third slow from the top, correct? It seems a bit strange that we calculate threshold instead of just marking N top slowest disks.

**Review by alexvru — CHANGES_REQUESTED** [review]

File: ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp (hunk 11 above)
Comment (serbel324) [reply ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp:565]: We only want to mark N slowest disks as "slow", if they are at least twice as slow as worst "normal" disk, that's why we need a threshold

File: ydb/core/blobstorage/dsproxy/dsproxy_strategy_get_m3dc_basic.h [hunk 12]
```diff
@@ -71,35 +71,13 @@ namespace NKikimr {
...
-                        break;
-                    }
-                    case TBlackboard::AccelerationModeSkipMarked:
-                        // The slowest disk is already marked!
-                        break;
-                }
+            // mark slow disks
+            switch (blackboard.AccelerationMode) {
+                case TBlackboard::AccelerationModeSkipNSlowest:
+                    blackboard.MarkSlowDisks(state, false, accelerationParams);
```
Comment (alexvru) [inline ydb/core/blobstorage/dsproxy/dsproxy_strategy_get_m3dc_basic.h:77]: break / [[fallthrough]];

**Review by alexvru — CHANGES_REQUESTED** [review]

**Review by alexvru — APPROVED** [review]
