### PR TITLE
Catching exceptions

### LINKED ISSUE #13728: Restoring data with --import-data doesn't work and doesn't throw an error
Summary:

Restoring data into an existing table with secondary indexes using `--import-data` should end with an error. But when user tries to use `ydb tools restore --import-data` with such conditions provided, they don't get any error message, which is confusing. Import is not happening either.

CLI version:
2.18.0

YDB version:
stable-24-3-13-hotfix-7

Steps to reproduce:
<details><summary>Details</summary>
<p>

This example demonstrates dumping a table from one directory and restoring it into the same table in another directory.

Creating a source table with indexes, filling it with data and dumping the directory.

```
CREATE TABLE `source/episodes`
(
    series_id Uint64,
    season_id Uint64,
    episode_id Uint64,
    title Utf8,
    air_date Uint64,
    PRIMARY KEY (series_id, season_id, episode_id)
);
```

```
ALTER TABLE `source/episodes` ADD INDEX `episodes_title_ix` GLOBAL ON (`title`);
```

```
ALTER TABLE `source/episodes` ADD INDEX `episodes_air_date_ix` GLOBAL ON (`air_date`);
```

```
REPLACE INTO `source/episodes` (series_id, season_id, episode_id, title, air_date)
VALUES
    (1, 1, 1, "Yesterday's Jam", CAST(Date("2006-02-03") AS Uint64)),
    (1, 1, 2, "Calamity Jen", CAST(Date("2006-02-03") AS Uint64)),
    (1, 1, 3, "Fifty-Fifty", CAST(Date("2006-02-10") AS Uint64));
```

```
ydb tools dump -p source
```

Creating the same table and indexes in the target directory. Filling it with different data.

```
CREATE TABLE `target/episodes`
(
    series_id Uint64,
    season_id Uint64,
    episode_id Uint64,
    title Utf8,
    air_date Uint64,
    PRIMARY KEY (series_id, season_id, episode_id)
);
```

```
ALTER TABLE `target/episodes` ADD INDEX `episodes_title_ix` GLOBAL ON (`title`);
```

```
ALTER TABLE `target/episodes` ADD INDEX `episodes_air_date_ix` GLOBAL ON (`air_date`);
```

```
REPLACE INTO `target/episodes` (series_id, season_id, episode_id, title, air_date)
VALUES
    (1, 3, 1, "From Hell", CAST(Date("2008-11-21") AS Uint64)),
    (1, 3, 2, "Are We Not Men?", CAST(Date("2008-11-28") AS Uint64)),
    (1, 3, 3, "Tramps Like Us", CAST(Date("2008-12-05") AS Uint64));
```

Doing the restore with --import-data option

```
ydb tools restore -p target --import-data
```
</p>
</details> 

Expected result:
Import ends with an error

Actual result:
Import ends without an error. But the data is not imported to the table either.

### PR DESCRIPTION
**Pull request by CyberROFL**
### Changelog entry 

Fixed a bug where some errors could be ignored when restoring from a local backup.

### Changelog category 

* Bugfix

### Additional information

...

### CODE REVIEW

**Review by Gazizonoki — APPROVED** [review]
SDK LGTM

**Review by pnv1 — APPROVED** [review]

File: ydb/public/lib/ydb_cli/dump/restore_import_data.cpp [hunk 1]
```diff
@@ -406,7 +406,14 @@ class TKeyBuilder {
...
 
             TYdbDumpValueParser parser(value, GetPrimitiveType(column.Type));
-            values.emplace(it->second, TValueConverter<TYdbDumpValueParser>(parser).ConvertSingle());
+            try {
+                values.emplace(it->second, TValueConverter<TYdbDumpValueParser>(parser).ConvertSingle());
+            } catch (const TFromStringException& e) {
+                auto loc = TStringBuilder() << line.GetLocation();
+                throw NStatusHelpers::TYdbErrorException(Result<TStatus>(loc, EStatus::SCHEME_ERROR, e.what()));
+            } catch (...) {
+                std::rethrow_exception(std::current_exception());
```
Comment (pixcc) [inline ydb/public/lib/ydb_cli/dump/restore_import_data.cpp:415]: Minor:
```suggestion
                throw;
```

**Review by pixcc — APPROVED** [review]
