### PR TITLE
Fix ignored messages on CS table rename

### LINKED ISSUE #23564: [stable-25-3-1] VERIFY failed schemeshard__operation_part.cpp:108
Отстрелила верифайка при ночном прогоне немезиса с ворклоудами

- simple_queue
  - [DDL](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/simple_queue/workload/__init__.py#L110)
- olap
  - [DDL Insert delete](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/olap_workload/workload/type/insert_delete.py#L23) 
  - [DDL Rename](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/olap_workload/workload/type/rename_tables.py#L20)
  - [DDL Create drop](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/olap_workload/workload/type/tables_create_drop.py#L67)
  - [DDL Transactions](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/olap_workload/workload/type/transactions.py#L16)
- oltp
  - [DDL Insert detele all types](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/oltp_workload/workload/type/insert_delete_all_types.py#L25)
  - [DDL Vector Index](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/oltp_workload/workload/type/vector_index.py#L70)
- node_broker
- transfer
  - [DDL](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/transfer/workload/__init__.py#L26)
- topic_kafka
- kafka
- ctas
  - [DDL](https://github.com/ydb-platform/ydb/blob/1289b29d29b67c886b61b3713ef6be19fd1e26bc/ydb/tests/stress/ctas/workload/__init__.py#L60)
- log
- topic

[Cluster config](https://nda.ya.ru/t/CA0kZKPf7J7Pze)
Версия: stable-25-1-4.430eece

<details>
  <summary>Текст верифайки</summary>

```
VERIFY failed (2025-08-25T23:58:28.016814+0300): Unexpected message: tablet# 72075186224037897, ev# Status: PREPARED TxKind: TX_KIND_SCHEMA Origin: 72075186224051974 TxId: 844424930600420 MinStep: 0 MaxStep: 18446744073709551615 StatusMessage: "success on iteration before restart" DomainCoordinators: 72075186224037895 DomainCoordinators: 72075186224037893 DomainCoordinators: 72075186224037896
  ydb/core/tx/schemeshard/schemeshard__operation_part.cpp:108
  HandleReply(): requirement false failed
0. /-S/util/system/yassert.cpp:83: InternalPanicImpl @ 0x1DB8AB88
1. /-S/util/system/yassert.cpp:55: Panic @ 0x1DB7BB4A
2. /tmp//-S/ydb/core/tx/schemeshard/schemeshard__operation_part.cpp:108: HandleReply @ 0x28D7621A
3. /-S/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:118: __invoke<bool (NKikimr::NSchemeShard::ISubOperationState::*&)(TAutoPtr<NActors::TEventHandle<NKikimr::TEvColumnShard::TEvProposeTransactionResult>, TDelete> &, NKikimr::NSchemeShard::TOperationContext &), NKikimr::NSchemeShard::TSubOperationState *, TAutoPtr<NActors::TEventHandle<NKikimr::TEvColumnShard::TEvProposeTransactionResult>, TDelete> &, NKikimr::NSchemeShard::TOperationContext &, void> @ 0x28D764A8
4. /-S/contrib/libs/cxxsupp/libcxx/include/__functional/invoke.h:28: invoke<bool (NKikimr::NSchemeShard::ISubOperationState::*&)(TAutoPtr<NActors::TEventHandle<NKikimr::TEvColumnShard::TEvProposeTransactionResult>, TDelete> &, NKikimr::NSchemeShard::TOperationContext &), NKikimr::NSchemeShard::TSubOperationState *, TAutoPtr<NActors::TEventHandle<NKikimr::TEvColumnShard::TEvProposeTransactionResult>, TDelete> &, NKikimr::NSchemeShard::TOperationContext &> @ 0x28D764A8
5. /-S/ydb/core/tx/schemeshard/schemeshard__operation_part.h:307: Progress<TAutoPtr<NActors::TEventHandle<NKikimr::TEvColumnShard::TEvProposeTransactionResult>, TDelete> &> @ 0x28D764A8
6. /tmp//-S/ydb/core/tx/schemeshard/schemeshard__operation_part.cpp:108: HandleReply @ 0x28D764A8
7. /tmp//-S/ydb/core/tx/schemeshard/schemeshard__operation.cpp:625: Execute @ 0x2852860E
8. /tmp//-S/ydb/core/tablet_flat/flat_executor.cpp:1765: ExecuteTransaction @ 0x250CA1EC
9. /tmp//-S/ydb/core/tablet_flat/flat_executor.cpp:1737: DoExecute @ 0x250C591F
10. /tmp//-S/ydb/core/tablet_flat/flat_executor.cpp:1741: Execute @ 0x250CCE44
11. /tmp//-S/ydb/core/tablet_flat/tablet_flat_executed.cpp:39: Execute @ 0x2507138A
12. /tmp//-S/ydb/core/tablet_flat/tablet_flat_executed.cpp:34: Execute @ 0x2507138A
13. /tmp//-S/ydb/core/tx/schemeshard/schemeshard_impl.cpp:6114: Handle @ 0x291B31F3
14. /tmp//-S/ydb/core/tx/schemeshard/schemeshard_impl.cpp:4869: StateWork @ 0x290F535F
15. /-S/ydb/library/actors/core/actor.h:614: Receive @ 0x2019B2FC
16. /tmp//-S/ydb/library/actors/core/executor_thread.cpp:269: Execute @ 0x20195938
17. /tmp//-S/ydb/library/actors/core/executor_thread.cpp:460: operator() @ 0x2019E22E
18. /tmp//-S/ydb/library/actors/core/executor_thread.cpp:512: ProcessExecutorPool @ 0x2019D789
19. /tmp//-S/ydb/library/actors/core/executor_thread.cpp:538: ThreadProc @ 0x2019F7DE
20. /-S/util/system/thread.cpp:244: ThreadProxy @ 0x1DB96CC4
21. /tmp//-S/contrib/libs/clang18-rt/lib/asan/asan_interceptors.cpp:239: asan_thread_start @ 0x1D83E7D8
22. ??:0: ?? @ 0x7F2D733E6608
23. ??:0: ?? @ 0x7F2D7330B352
```

</details>

### PR DESCRIPTION
**Pull request by zverevgeny**
Fixup to:
- https://github.com/ydb-platform/ydb/pull/16961

### Changelog category 
* Not for changelog (changelog entry is not required)

### CODE REVIEW

File: ydb/core/tx/schemeshard/schemeshard__operation_move_table.cpp [hunk 1]
```diff
@@ -346,7 +346,7 @@ class TWaitRenamedPathPublication: public TSubOperationState {
     TWaitRenamedPathPublication(TOperationId id)
         : OperationId(id)
     {
-        IgnoreMessages(DebugHint(), {TEvHive::TEvCreateTabletReply::EventType, TEvDataShard::TEvProposeTransactionResult::EventType, TEvPrivate::TEvOperationPlan::EventType});
+        IgnoreMessages(DebugHint(), {TEvHive::TEvCreateTabletReply::EventType, TEvDataShard::TEvProposeTransactionResult::EventType, TEvPrivate::TEvOperationPlan::EventType, TEvColumnShard::TEvProposeTransactionResult::EventType});
```
Comment (CyberROFL) [inline ydb/core/tx/schemeshard/schemeshard__operation_move_table.cpp]:
```suggestion
        IgnoreMessages(DebugHint(), {
            TEvHive::TEvCreateTabletReply::EventType,
            TEvDataShard::TEvProposeTransactionResult::EventType,
            TEvColumnShard::TEvProposeTransactionResult::EventType,
            TEvPrivate::TEvOperationPlan::EventType,
        });
```

File: ydb/core/tx/schemeshard/schemeshard__operation_move_table.cpp [hunk 2]
```diff
@@ -434,7 +434,7 @@ class TDeleteTableBarrier: public TSubOperationState {
     TDeleteTableBarrier(TOperationId id)
         : OperationId(id)
     {
-        IgnoreMessages(DebugHint(), {TEvHive::TEvCreateTabletReply::EventType, TEvDataShard::TEvProposeTransactionResult::EventType, TEvPrivate::TEvOperationPlan::EventType});
+        IgnoreMessages(DebugHint(), {TEvHive::TEvCreateTabletReply::EventType, TEvDataShard::TEvProposeTransactionResult::EventType, TEvPrivate::TEvOperationPlan::EventType, TEvColumnShard::TEvProposeTransactionResult::EventType});
```
Comment (CyberROFL) [inline ydb/core/tx/schemeshard/schemeshard__operation_move_table.cpp]:
```suggestion
        IgnoreMessages(DebugHint(), {
            TEvHive::TEvCreateTabletReply::EventType,
            TEvDataShard::TEvProposeTransactionResult::EventType,
            TEvColumnShard::TEvProposeTransactionResult::EventType,
            TEvPrivate::TEvOperationPlan::EventType,
        });
```

**Review by CyberROFL — APPROVED** [review]
