### PR TITLE
Fix actor system usage after it was freed

### LINKED ISSUE #7282: [Viewer] AddressSanitizer: heap-use-after-free NActors::TAsyncHttpMon::Stop() ydb/core/mon/async_http_mon.cpp:809:26
```
warning: address range table at offset 0x1630 has a premature terminator entry at offset 0x1640
    #0 0x17b1aafc in __asan_memcpy /-S/contrib/libs/clang16-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3
    #1 0x18e8c544 in NActors::IEventHandle::IEventHandle /-S/contrib/ydb/library/actors/core/event.h:204:15
    #2 0x18e8c544 in NActors::TActorSystem::Send(NActors::TActorId const&, NActors::IEventBase*, unsigned int, unsigned long) const /-S/contrib/ydb/library/actors/core/actorsystem.cpp:159:31
    #3 0x38776ca5 in NActors::TAsyncHttpMon::Stop() /-S/contrib/ydb/core/mon/async_http_mon.cpp:809:26
    #4 0x3871f277 in NActors::TTestActorRuntime::TNodeData::Stop /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:28:18
    #5 0x3871f277 in NActors::TTestActorRuntime::TNodeData::~TNodeData /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:33:9
    #6 0x3871f277 in NActors::TTestActorRuntime::TNodeData::~TNodeData() /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:32:48
    #7 0x38548034 in CheckedDelete<TThrRefBase> /-S/util/generic/ptr.h:36:5
    #8 0x38548034 in TDelete::Destroy<TThrRefBase> /-S/util/generic/ptr.h:57:9
    #9 0x38548034 in TRefCounted<TThrRefBase, TAtomicCounter, TDelete>::UnRef /-S/util/generic/ptr.h:386:13
    #10 0x38548034 in TRefCounted<TThrRefBase, TAtomicCounter, TDelete>::UnRef /-S/util/generic/ptr.h:391:9
    #11 0x38548034 in TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>::UnRef /-S/util/generic/ptr.h:462:12
    #12 0x38548034 in TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> >::UnRef /-S/util/generic/ptr.h:599:13
    #13 0x38548034 in TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> >::~TIntrusivePtr /-S/util/generic/ptr.h:504:9
    #14 0x38548034 in std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >::~pair /-S/contrib/libs/cxxsupp/libcxx/include/stlfwd:14:12
    #15 0x38548034 in std::__y1::__destroy_at<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, 0> /-S/contrib/libs/cxxsupp/libcxx/include/__memory/construct_at.h:69:13
    #16 0x38548034 in std::__y1::destroy_at<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, 0> /-S/contrib/libs/cxxsupp/libcxx/include/__memory/construct_at.h:104:5
    #17 0x38548034 in std::__y1::allocator_traits<std::__y1::allocator<std::__y1::__tree_node<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, void *> > >::destroy<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, void, void> /-S/contrib/libs/cxxsupp/libcxx/include/__memory/allocator_traits.h:323:9
    #18 0x38548034 in std::__y1::__tree<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>, std::__y1::__map_value_compare<unsigned int, std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>, TLess<unsigned int>, true>, std::__y1::allocator<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>>>::destroy(std::__y1::__tree_node<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>, void*>*) /-S/contrib/libs/cxxsupp/libcxx/include/__tree:1815:9
    #19 0x3851f38c in std::__y1::__tree<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, std::__y1::__map_value_compare<unsigned int, std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, TLess<unsigned int>, true>, std::__y1::allocator<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > > > >::clear /-S/contrib/libs/cxxsupp/libcxx/include/__tree:1852:5
    #20 0x3851f38c in std::__y1::map<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> >, TLess<unsigned int>, std::__y1::allocator<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > > > >::clear /-S/contrib/libs/cxxsupp/libcxx/include/map:1460:37
    #21 0x3851f38c in NActors::TTestActorRuntimeBase::CleanupNodes() /-S/contrib/ydb/library/actors/testlib/test_runtime.cpp:574:15
    #22 0x387210b1 in NActors::TTestActorRuntime::~TTestActorRuntime() /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:90:9
    #23 0x3895713e in NActors::TTestBasicRuntime::~TTestBasicRuntime /-S/contrib/ydb/core/testlib/basics/runtime.cpp:15:5
    #24 0x3895713e in NActors::TTestBasicRuntime::~TTestBasicRuntime() /-S/contrib/ydb/core/testlib/basics/runtime.cpp:13:5
    #25 0x38831e1b in CheckedDelete<NActors::TTestActorRuntime> /-S/util/generic/ptr.h:36:5
    #26 0x38831e1b in TDelete::Destroy<NActors::TTestActorRuntime> /-S/util/generic/ptr.h:57:9
    #27 0x38831e1b in THolder<NActors::TTestActorRuntime, TDelete>::DoDestroy /-S/util/generic/ptr.h:341:13
    #28 0x38831e1b in THolder<NActors::TTestActorRuntime, TDelete>::Reset /-S/util/generic/ptr.h:291:13
    #29 0x38831e1b in THolder<NActors::TTestActorRuntime, TDelete>::Destroy /-S/util/generic/ptr.h:282:9
    #30 0x38831e1b in NKikimr::Tests::TServer::~TServer() /-S/contrib/ydb/core/testlib/test_client.cpp:1237:21
    #31 0x17a1581b in NTestSuiteViewer::TTestCaseAuthorizeYdbTokenWithDatabaseAttributes::Execute_(NUnitTest::TTestContext&) /-S/contrib/ydb/core/viewer/viewer_ut.cpp:1647:5
    #32 0x17a27638 in NTestSuiteViewer::TCurrentTest::Execute()::(anonymous class)::operator() /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1
    #33 0x17a27638 in std::__y1::__invoke<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1) &> /-S/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:344:25
    #34 0x17a27638 in std::__y1::__invoke_void_return_wrapper<void, true>::__call<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1) &> /-S/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:419:5
    #35 0x17a27638 in std::__y1::__function::__alloc_func<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1), std::__y1::allocator<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1)>, void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:195:16
    #36 0x17a27638 in std::__y1::__function::__func<NTestSuiteViewer::TCurrentTest::Execute()::'lambda'(), std::__y1::allocator<NTestSuiteViewer::TCurrentTest::Execute()::'lambda'()>, void ()>::operator()() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:366:12
    #37 0x1818e17a in std::__y1::__function::__value_func<void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:519:16
    #38 0x1818e17a in std::__y1::function<void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:1170:12
    #39 0x1818e17a in TColoredProcessor::Run(std::__y1::function<void ()>, TBasicString<char, std::__y1::char_traits<char>> const&, char const*, bool) /-S/library/cpp/testing/unittest/utmain.cpp:525:20
    #40 0x1814e405 in NUnitTest::TTestBase::Run(std::__y1::function<void ()>, TBasicString<char, std::__y1::char_traits<char>> const&, char const*, bool) /-S/library/cpp/testing/unittest/registar.cpp:374:18
    #41 0x17a25f63 in NTestSuiteViewer::TCurrentTest::Execute() /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1
    #42 0x18150149 in NUnitTest::TTestFactory::Execute() /-S/library/cpp/testing/unittest/registar.cpp:495:19
    #43 0x181865ec in NUnitTest::RunMain(int, char**) /-S/library/cpp/testing/unittest/utmain.cpp:872:44
    #44 0x7fbced756082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
    #45 0x154b4028 in _start (/storage/d/b/3ccc029c-82239321-687b4c26-5066a-0/43/test-11608630263273278401-2AC/f0a9/contrib/ydb/core/viewer/ut/contrib-ydb-core-viewer-ut+0x154b4028) (BuildId: 62fb83e179077c7cd530fa5f2d11209ef7d0c305)
0x612000022128 is located 104 bytes inside of 288-byte region [0x6120000220c0,0x6120000221e0)
freed by thread T0 here:
    #0 0x17b4cd4d in operator delete(void*) /-S/contrib/libs/clang16-rt/lib/asan/asan_new_delete.cpp:152:3
    #1 0x385140e7 in CheckedDelete<NActors::TActorSystem> /-S/util/generic/ptr.h:36:5
    #2 0x385140e7 in TDelete::Destroy<NActors::TActorSystem> /-S/util/generic/ptr.h:57:9
    #3 0x385140e7 in THolder<NActors::TActorSystem, TDelete>::DoDestroy /-S/util/generic/ptr.h:341:13
    #4 0x385140e7 in THolder<NActors::TActorSystem, TDelete>::Reset /-S/util/generic/ptr.h:291:13
    #5 0x385140e7 in THolder<NActors::TActorSystem, TDelete>::Destroy /-S/util/generic/ptr.h:282:9
    #6 0x385140e7 in NActors::TTestActorRuntimeBase::TNodeDataBase::Stop() /-S/contrib/ydb/library/actors/testlib/test_runtime.cpp:76:21
    #7 0x3871f222 in NActors::TTestActorRuntime::TNodeData::Stop /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:26:24
    #8 0x3871f222 in NActors::TTestActorRuntime::TNodeData::~TNodeData /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:33:9
    #9 0x3871f222 in NActors::TTestActorRuntime::TNodeData::~TNodeData() /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:32:48
    #10 0x38548034 in CheckedDelete<TThrRefBase> /-S/util/generic/ptr.h:36:5
    #11 0x38548034 in TDelete::Destroy<TThrRefBase> /-S/util/generic/ptr.h:57:9
    #12 0x38548034 in TRefCounted<TThrRefBase, TAtomicCounter, TDelete>::UnRef /-S/util/generic/ptr.h:386:13
    #13 0x38548034 in TRefCounted<TThrRefBase, TAtomicCounter, TDelete>::UnRef /-S/util/generic/ptr.h:391:9
    #14 0x38548034 in TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>::UnRef /-S/util/generic/ptr.h:462:12
    #15 0x38548034 in TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> >::UnRef /-S/util/generic/ptr.h:599:13
    #16 0x38548034 in TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> >::~TIntrusivePtr /-S/util/generic/ptr.h:504:9
    #17 0x38548034 in std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >::~pair /-S/contrib/libs/cxxsupp/libcxx/include/stlfwd:14:12
    #18 0x38548034 in std::__y1::__destroy_at<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, 0> /-S/contrib/libs/cxxsupp/libcxx/include/__memory/construct_at.h:69:13
    #19 0x38548034 in std::__y1::destroy_at<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, 0> /-S/contrib/libs/cxxsupp/libcxx/include/__memory/construct_at.h:104:5
    #20 0x38548034 in std::__y1::allocator_traits<std::__y1::allocator<std::__y1::__tree_node<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, void *> > >::destroy<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, void, void> /-S/contrib/libs/cxxsupp/libcxx/include/__memory/allocator_traits.h:323:9
    #21 0x38548034 in std::__y1::__tree<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>, std::__y1::__map_value_compare<unsigned int, std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>, TLess<unsigned int>, true>, std::__y1::allocator<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>>>::destroy(std::__y1::__tree_node<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase>>>, void*>*) /-S/contrib/libs/cxxsupp/libcxx/include/__tree:1815:9
    #22 0x3851f38c in std::__y1::__tree<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, std::__y1::__map_value_compare<unsigned int, std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > >, TLess<unsigned int>, true>, std::__y1::allocator<std::__y1::__value_type<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > > > >::clear /-S/contrib/libs/cxxsupp/libcxx/include/__tree:1852:5
    #23 0x3851f38c in std::__y1::map<unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> >, TLess<unsigned int>, std::__y1::allocator<std::__y1::pair<const unsigned int, TIntrusivePtr<NActors::TTestActorRuntimeBase::TNodeDataBase, TDefaultIntrusivePtrOps<NActors::TTestActorRuntimeBase::TNodeDataBase> > > > >::clear /-S/contrib/libs/cxxsupp/libcxx/include/map:1460:37
    #24 0x3851f38c in NActors::TTestActorRuntimeBase::CleanupNodes() /-S/contrib/ydb/library/actors/testlib/test_runtime.cpp:574:15
    #25 0x387210b1 in NActors::TTestActorRuntime::~TTestActorRuntime() /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:90:9
    #26 0x3895713e in NActors::TTestBasicRuntime::~TTestBasicRuntime /-S/contrib/ydb/core/testlib/basics/runtime.cpp:15:5
    #27 0x3895713e in NActors::TTestBasicRuntime::~TTestBasicRuntime() /-S/contrib/ydb/core/testlib/basics/runtime.cpp:13:5
    #28 0x38831e1b in CheckedDelete<NActors::TTestActorRuntime> /-S/util/generic/ptr.h:36:5
    #29 0x38831e1b in TDelete::Destroy<NActors::TTestActorRuntime> /-S/util/generic/ptr.h:57:9
    #30 0x38831e1b in THolder<NActors::TTestActorRuntime, TDelete>::DoDestroy /-S/util/generic/ptr.h:341:13
    #31 0x38831e1b in THolder<NActors::TTestActorRuntime, TDelete>::Reset /-S/util/generic/ptr.h:291:13
    #32 0x38831e1b in THolder<NActors::TTestActorRuntime, TDelete>::Destroy /-S/util/generic/ptr.h:282:9
    #33 0x38831e1b in NKikimr::Tests::TServer::~TServer() /-S/contrib/ydb/core/testlib/test_client.cpp:1237:21
    #34 0x17a1581b in NTestSuiteViewer::TTestCaseAuthorizeYdbTokenWithDatabaseAttributes::Execute_(NUnitTest::TTestContext&) /-S/contrib/ydb/core/viewer/viewer_ut.cpp:1647:5
    #35 0x17a27638 in NTestSuiteViewer::TCurrentTest::Execute()::(anonymous class)::operator() /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1
    #36 0x17a27638 in std::__y1::__invoke<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1) &> /-S/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:344:25
    #37 0x17a27638 in std::__y1::__invoke_void_return_wrapper<void, true>::__call<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1) &> /-S/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:419:5
    #38 0x17a27638 in std::__y1::__function::__alloc_func<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1), std::__y1::allocator<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1)>, void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:195:16
    #39 0x17a27638 in std::__y1::__function::__func<NTestSuiteViewer::TCurrentTest::Execute()::'lambda'(), std::__y1::allocator<NTestSuiteViewer::TCurrentTest::Execute()::'lambda'()>, void ()>::operator()() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:366:12
    #40 0x1818e17a in std::__y1::__function::__value_func<void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:519:16
    #41 0x1818e17a in std::__y1::function<void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:1170:12
    #42 0x1818e17a in TColoredProcessor::Run(std::__y1::function<void ()>, TBasicString<char, std::__y1::char_traits<char>> const&, char const*, bool) /-S/library/cpp/testing/unittest/utmain.cpp:525:20
    #43 0x1814e405 in NUnitTest::TTestBase::Run(std::__y1::function<void ()>, TBasicString<char, std::__y1::char_traits<char>> const&, char const*, bool) /-S/library/cpp/testing/unittest/registar.cpp:374:18
    #44 0x17a25f63 in NTestSuiteViewer::TCurrentTest::Execute() /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1
    #45 0x18150149 in NUnitTest::TTestFactory::Execute() /-S/library/cpp/testing/unittest/registar.cpp:495:19
    #46 0x181865ec in NUnitTest::RunMain(int, char**) /-S/library/cpp/testing/unittest/utmain.cpp:872:44
    #47 0x7fbced756082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
previously allocated by thread T0 here:
warning: address range table at offset 0x0 has a premature terminator entry at offset 0x10
warning: address range table at offset 0x30 has a premature terminator entry at offset 0x40
warning: address range table at offset 0x60 has a premature terminator entry at offset 0x70
warning: address range table at offset 0x90 has a premature terminator entry at offset 0xa0
warning: address range table at offset 0xc0 has a premature terminator entry at offset 0xd0
warning: address range table at offset 0xa20 has a premature terminator entry at offset 0xa30
warning: address range table at offset 0xa50 has a premature terminator entry at offset 0xa60
warning: address range table at offset 0xa80 has a premature terminator entry at offset 0xa90
warning: address range table at offset 0xab0 has a premature terminator entry at offset 0xac0
warning: address range table at offset 0xae0 has a premature terminator entry at offset 0xaf0
warning: address range table at offset 0xb10 has a premature terminator entry at offset 0xb20
warning: address range table at offset 0xb40 has a premature terminator entry at offset 0xb50
warning: address range table at offset 0xb70 has a premature terminator entry at offset 0xb80
warning: address range table at offset 0xba0 has a premature terminator entry at offset 0xbb0
warning: address range table at offset 0xbd0 has a premature terminator entry at offset 0xbe0
warning: address range table at offset 0xc00 has a premature terminator entry at offset 0xc10
warning: address range table at offset 0xc30 has a premature terminator entry at offset 0xc40
warning: address range table at offset 0xc60 has a premature terminator entry at offset 0xc70
warning: address range table at offset 0xc90 has a premature terminator entry at offset 0xca0
warning: address range table at offset 0xcc0 has a premature terminator entry at offset 0xcd0
warning: address range table at offset 0xcf0 has a premature terminator entry at offset 0xd00
warning: address range table at offset 0xd20 has a premature terminator entry at offset 0xd30
warning: address range table at offset 0x12d0 has a premature terminator entry at offset 0x12e0
warning: address range table at offset 0x1300 has a premature terminator entry at offset 0x1310
warning: address range table at offset 0x1330 has a premature terminator entry at offset 0x1340
warning: address range table at offset 0x1390 has a premature terminator entry at offset 0x13a0
warning: address range table at offset 0x13c0 has a premature terminator entry at offset 0x13d0
warning: address range table at offset 0x13f0 has a premature terminator entry at offset 0x1400
warning: address range table at offset 0x1420 has a premature terminator entry at offset 0x1430
warning: address range table at offset 0x1450 has a premature terminator entry at offset 0x1460
warning: address range table at offset 0x15a0 has a premature terminator entry at offset 0x15b0
warning: address range table at offset 0x15d0 has a premature terminator entry at offset 0x15e0
warning: address range table at offset 0x1600 has a premature terminator entry at offset 0x1610
warning: address range table at offset 0x1630 has a premature terminator entry at offset 0x1640
    #0 0x17b4c4ed in operator new(unsigned long) /-S/contrib/libs/clang16-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x3851cc61 in NActors::TTestActorRuntimeBase::MakeActorSystem(unsigned int, NActors::TTestActorRuntimeBase::TNodeDataBase*) /-S/contrib/ydb/library/actors/testlib/test_runtime.cpp:1781:38
    #2 0x38722e93 in NActors::TTestActorRuntime::Initialize(NActors::TTestActorRuntime::TEgg) /-S/contrib/ydb/core/testlib/actors/test_runtime.cpp:129:37
    #3 0x389573f6 in NActors::TTestBasicRuntime::Initialize(NActors::TTestActorRuntime::TEgg) /-S/contrib/ydb/core/testlib/basics/runtime.cpp:21:28
    #4 0x38bc7a62 in NKikimr::SetupBasicServices(NActors::TTestActorRuntime&, NKikimr::TAppPrepare&, bool, NKikimr::NFake::INode*, NKikimr::NFake::TStorage, NKikimr::NFake::TCaches, bool) /-S/contrib/ydb/core/testlib/basics/services.cpp:381:17
    #5 0x389cd28e in NKikimr::SetupTabletServices(NActors::TTestActorRuntime&, NKikimr::TAppPrepare*, bool, NKikimr::NFake::TStorage, NKikimr::NFake::TCaches, bool) /-S/contrib/ydb/core/testlib/tablet_helpers.cpp:637:9
    #6 0x387ec83d in NKikimr::Tests::TServer::Initialize() /-S/contrib/ydb/core/testlib/test_client.cpp:262:9
    #7 0x387ea8f2 in NKikimr::Tests::TServer::TServer(TIntrusiveConstPtr<NKikimr::Tests::TServerSettings, TDefaultIntrusivePtrOps<NKikimr::Tests::TServerSettings>>, bool) /-S/contrib/ydb/core/testlib/test_client.cpp:166:13
    #8 0x387ed4e3 in NKikimr::Tests::TServer::TServer(NKikimr::Tests::TServerSettings const&, bool) /-S/contrib/ydb/core/testlib/test_client.cpp:170:11
    #9 0x17a11501 in NTestSuiteViewer::TTestCaseAuthorizeYdbTokenWithDatabaseAttributes::Execute_(NUnitTest::TTestContext&) /-S/contrib/ydb/core/viewer/viewer_ut.cpp:1614:17
    #10 0x17a27638 in NTestSuiteViewer::TCurrentTest::Execute()::(anonymous class)::operator() /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1
    #11 0x17a27638 in std::__y1::__invoke<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1) &> /-S/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:344:25
    #12 0x17a27638 in std::__y1::__invoke_void_return_wrapper<void, true>::__call<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1) &> /-S/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:419:5
    #13 0x17a27638 in std::__y1::__function::__alloc_func<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1), std::__y1::allocator<(lambda at /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1)>, void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:195:16
    #14 0x17a27638 in std::__y1::__function::__func<NTestSuiteViewer::TCurrentTest::Execute()::'lambda'(), std::__y1::allocator<NTestSuiteViewer::TCurrentTest::Execute()::'lambda'()>, void ()>::operator()() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:366:12
    #15 0x1818e17a in std::__y1::__function::__value_func<void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:519:16
    #16 0x1818e17a in std::__y1::function<void ()>::operator() /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:1170:12
    #17 0x1818e17a in TColoredProcessor::Run(std::__y1::function<void ()>, TBasicString<char, std::__y1::char_traits<char>> const&, char const*, bool) /-S/library/cpp/testing/unittest/utmain.cpp:525:20
    #18 0x1814e405 in NUnitTest::TTestBase::Run(std::__y1::function<void ()>, TBasicString<char, std::__y1::char_traits<char>> const&, char const*, bool) /-S/library/cpp/testing/unittest/registar.cpp:374:18
    #19 0x17a25f63 in NTestSuiteViewer::TCurrentTest::Execute() /-S/contrib/ydb/core/viewer/viewer_ut.cpp:68:1
    #20 0x18150149 in NUnitTest::TTestFactory::Execute() /-S/library/cpp/testing/unittest/registar.cpp:495:19
    #21 0x181865ec in NUnitTest::RunMain(int, char**) /-S/library/cpp/testing/unittest/utmain.cpp:872:44
    #22 0x7fbced756082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
```

### PR DESCRIPTION
**Pull request by UgnineSirdis**
### Changelog entry 

Problems affects test actor system

### Changelog category 

* Not for changelog (changelog entry is not required)

### Additional information

...

### CODE REVIEW

File: ydb/core/testlib/actors/test_runtime.cpp [hunk 1]
```diff
@@ -24,10 +24,10 @@
 namespace NActors {
 
     void TTestActorRuntime::TNodeData::Stop() {
-        TNodeDataBase::Stop();
         if (Mon) {
             Mon->Stop();
```
Comment (SammyVimes) [inline ydb/core/testlib/actors/test_runtime.cpp:28]:
```suggestion
            Mon->Stop();
            GetAppData<NKikimr::TAppData>()->Mon = nullptr;
```

**Review by SammyVimes — CHANGES_REQUESTED** [review]

**Review by SammyVimes — APPROVED** [review]
LGTM!
