### PR TITLE
Fix TX proxy and add bridge mode stress test for scheme board

### LINKED ISSUE #20646: Bridge Mode in SB: stress tests on concurrent config changes and scheme modifications
Write a stress test that will:
1) Start a cluster in 2DC mode.
2) Change a state of one of the piles.
3) Concurrently create and drop tables to see potential bugs in Scheme Board.

Can be a copy paste of the Scheme Board reconfiguration stress [test](https://github.com/ydb-platform/ydb/blob/6adfabd2adef905e47ce6febd1c24aa1d897a5c9/ydb/tests/stress/reconfig_state_storage_workload/tests/test_scheme_board_workload.py#L6).

### PR DESCRIPTION
**Pull request by jepett0**
### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

Epic:
- https://github.com/ydb-platform/ydb/issues/19748

Issue:
- https://github.com/ydb-platform/ydb/issues/20646

The stress test and a fix in the TX proxy that make it stable enough.

#### TX proxy fix

TX proxy [resolves](https://github.com/ydb-platform/ydb/blob/c2d430629ddab8a78bc6d3f1640f7abf7c5532e9/ydb/core/tx/tx_proxy/schemereq.cpp#L503) working dir as follows:
1. /Root
2. /Root/db
3. /Root/db/dirA
4. /Root/db/dirA/dirB
5. /Root/db/dirA/dirB/parentDir

If the `parentDir` does not exist (which is valid), the SchemeCache resolution status for it will be "PathErrorUnknown". The code [attempts](https://github.com/ydb-platform/ydb/blob/c2d430629ddab8a78bc6d3f1640f7abf7c5532e9/ydb/core/tx/tx_proxy/schemereq.cpp#L1719) to take the grandparent (`dirB`) as the working dir in this case. However, resolution of the `dirB` might end in a LookupError and it needs to be retried:
```
node_11/logfile_lq886ruu.log:2025-08-26T14:48:20.874872Z :TX_PROXY_SCHEME_CACHE DEBUG: cache.cpp:266: Send result: self# [11:7542906179349556600:2350], recipient# [11:7542906179349556163:2348], result# { ErrorCount: 3 DatabaseName:  DomainOwnerId: 0 Instant: 0 ResultSet [{ Path: Root TableId: [18446744073709551615:18446744073709551615:0] RequestType: ByPath Operation: OpPath RedirectRequired: false ShowPrivatePath: false SyncVersion: true Status: LookupError Kind: KindUnknown DomainInfo <null> },{ Path: Root/test TableId: [18446744073709551615:18446744073709551615:0] RequestType: ByPath Operation: OpPath RedirectRequired: false ShowPrivatePath: false SyncVersion: true Status: LookupError Kind: KindUnknown DomainInfo <null> },{ Path: Root/test/create_drop TableId: [18446744073709551615:18446744073709551615:0] RequestType: ByPath Operation: OpPath RedirectRequired: false ShowPrivatePath: false SyncVersion: true Status: PathErrorUnknown Kind: KindUnknown DomainInfo <null> }] }
```

The current PR adds retries on LookupErrors of ancestors of the working dir to handle the issue.

### CODE REVIEW

File: ydb/core/tx/scheme_board/subscriber.cpp [hunk 1]
```diff
@@ -777,6 +789,7 @@ class TSubscriber: public TMonitorableActor<TDerived> {
     }
 
     bool MaybeRunVersionSync() {
+        SBS_LOG_T("MaybeRunVersionSync, delayed sync request: " << DelayedSyncRequest);
```
Comment (CyberROFL) [inline ydb/core/tx/scheme_board/subscriber.cpp]:
```suggestion
        SBS_LOG_T("MaybeRunVersionSync"
            << ": delayed sync request# " << DelayedSyncRequest);
```

**Review by CyberROFL — APPROVED** [review]
