### PR TITLE
Check iter index access slice bounds

### LINKED ISSUE #18151: VERIFY AdvanceNextPage(): requirement !queue.empty() failed
```
2025-05-08T17:17:53.512688+03:00 VERIFY failed (2025-05-08T17:17:53.512627+0300):
2025-05-08T17:17:53.512688+03:00   contrib/ydb/core/tablet_flat/flat_fwd_cache.h:482
2025-05-08T17:17:53.512688+03:00   AdvanceNextPage(): requirement !queue.empty() failed
2025-05-08T17:20:10.254166+03:00 0. /-S/util/system/yassert.cpp:55: NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...) @ 0x559F43C7C61B
2025-05-08T17:20:11.716080+03:00 1. /-S/contrib/ydb/core/tablet_flat/flat_fwd_cache.h:482: NKikimr::NTable::NFwd::TBTreeIndexCache::AdvanceNextPage(NKikimr::NTable::NFwd::TBTreeIndexCache::TLevel&, unsigned int) @ 0x559F47D0996A
2025-05-08T17:20:11.747555+03:00 2. /-S/contrib/ydb/core/tablet_flat/flat_fwd_cache.h:334: NKikimr::NTable::NFwd::TBTreeIndexCache::Get(NKikimr::NTable::NFwd::IPageLoadingQueue*, unsigned int, NKikimr::NTable::NPage::EPage, unsigned long) @ 0x559F47D0996A
2025-05-08T17:20:11.771071+03:00 3. /-S/contrib/ydb/core/tablet_flat/flat_fwd_env.h:276: NKikimr::NTable::NFwd::TEnv::Get(NKikimr::NTable::NFwd::TPartGroupLoadingQueue&, unsigned int, NKikimr::NTable::NPage::EPage) @ 0x559F47D11C6B
2025-05-08T17:20:11.771248+03:00 4. /-S/contrib/ydb/core/tablet_flat/flat_fwd_env.h:134: NKikimr::NTable::NFwd::TEnv::TryGetPage(NKikimr::NTable::TPart const*, unsigned int, NKikimr::NTable::NPage::TGroupId) @ 0x559F47D11B71
2025-05-08T17:20:11.872520+03:00 5. /-S/contrib/ydb/core/tablet_flat/flat_part_index_iter_bree_index.h:363: NKikimr::NTable::TPartGroupBtreeIndexIter::TryLoad(NKikimr::NTable::TPartGroupBtreeIndexIter::TNodeState&) @ 0x559F47C45CC3
2025-05-08T17:20:11.904304+03:00 6. /-S/contrib/ydb/core/tablet_flat/flat_part_index_iter_bree_index.h:198: NKikimr::NTable::TPartGroupBtreeIndexIter::Next() @ 0x559F47C45CC3
2025-05-08T17:20:12.048695+03:00 7. /-S/contrib/ydb/core/tablet_flat/flat_part_iter.h:192: NKikimr::NTable::TPartGroupKeyIter::Seek(TArrayRef<NKikimr::TCell const>, NKikimr::NTable::ESeek, NKikimr::NTable::TPartScheme::TGroupInfo const&, NKikimr::NTable::TKeyCellDefaults const*) @ 0x559F4350F3B6
2025-05-08T17:20:12.088913+03:00 8. /-S/contrib/ydb/core/tablet_flat/flat_part_iter.h:817: NKikimr::NTable::TPartIter::Seek(TArrayRef<NKikimr::TCell const>, NKikimr::NTable::ESeek) @ 0x559F4350ED60
2025-05-08T17:20:12.110337+03:00 9. /-S/contrib/ydb/core/tablet_flat/flat_part_iter.h:1456: NKikimr::NTable::TRunIter::Seek(TArrayRef<NKikimr::TCell const>, NKikimr::NTable::ESeek) @ 0x559F4350ED60
2025-05-08T17:20:12.110337+03:00 10. /-S/contrib/ydb/core/tablet_flat/flat_scan_feed.h:405: NKikimr::NTable::TFeed::SeekBoots() @ 0x559F47CFE57A
2025-05-08T17:20:12.124235+03:00 11. /-S/contrib/ydb/core/tablet_flat/flat_scan_feed.h:453: NKikimr::NTable::TFeed::Seek() @ 0x559F47CFE57A
2025-05-08T17:20:12.146768+03:00 12. /-S/contrib/ydb/core/tablet_flat/flat_scan_feed.h:71: NKikimr::NTable::TFeed::Process() @ 0x559F47CFE57A
2025-05-08T17:20:12.191067+03:00 13. /-S/contrib/ydb/core/tablet_flat/flat_scan_actor.h:470: NKikimr::NTabletFlatExecutor::NOps::TDriver::React() @ 0x559F47CFE57A
2025-05-08T17:20:12.226074+03:00 14. /-S/contrib/ydb/core/tablet_flat/flat_scan_actor.h:649: NKikimr::NTabletFlatExecutor::NOps::TDriver::Handle(TAutoPtr<NActors::TEventHandle<NKikimr::NSharedCache::TEvResult>, TDelete>&) @ 0x559F47CFCC9A
2025-05-08T17:20:12.254174+03:00 15. /-S/contrib/ydb/core/tablet_flat/flat_scan_actor.h:356: NKikimr::NTabletFlatExecutor::NOps::TDriver::StateWork(TAutoPtr<NActors::IEventHandle, TDelete>&) @ 0x559F47CFCC9A
2025-05-08T17:20:12.453333+03:00 16. /-S/contrib/ydb/library/actors/core/executor_thread.cpp:251: NActors::TGenericExecutorThread::TProcessingResult NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::THTSwapMailbox>(NActors::TMailboxTable::THTSwapMailbox*, unsigned int, bool) @ 0x559F44207DF0
2025-05-08T17:20:12.457800+03:00 17. /-S/contrib/ydb/library/actors/core/executor_thread.cpp:440: NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const @ 0x559F441FD84A
2025-05-08T17:20:12.516487+03:00 18. /-S/contrib/ydb/library/actors/core/executor_thread.cpp:493: NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*) @ 0x559F441FD09F
2025-05-08T17:20:12.547716+03:00 19. /-S/contrib/ydb/library/actors/core/executor_thread.cpp:524: NActors::TExecutorThread::ThreadProc() @ 0x559F441FE484
2025-05-08T17:20:12.583519+03:00 20. /-S/util/system/thread.cpp:244: (anonymous namespace)::TPosixThread::ThreadProxy(void*) @ 0x559F43C8A7F9
2025-05-08T17:20:12.583519+03:00 21. ??:0: ?? @ 0x7FD684BAE608
2025-05-08T17:20:12.583519+03:00 22. ??:0: ?? @ 0x7FD684ACE132
```

[Link to core](https://coredumps.yandex-team.ru/core_trace?core_id=108114117)

[Link to cores with same hash](https://coredumps.yandex-team.ru/core?core_hash=648604734281525042&itype=kikimr-3038047901.stable-24-4-4-hotfix-6.hardening)

Instance [ydb-ru-sas-1139.search.yandex.net](http://ydb-ru-sas-1139.search.yandex.net/)

Problem stack

```
0?? () libc-2.31.so
1NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...) () [util/system/yassert.cpp](https://a.yandex-team.ru/arc/trunk/arcadia/util/system/yassert.cpp?#L55) +55
2NKikimr::NTable::NFwd::TBTreeIndexCache::Get(NKikimr::NTable::NFwd::IPageLoadingQueue*, unsigned int, NKikimr::NTable::NPage::EPage, unsigned long) () [contrib/ydb/core/tablet_flat/flat_fwd_cache.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_fwd_cache.h?#L482) +482
3NKikimr::NTable::NFwd::TEnv::Get(NKikimr::NTable::NFwd::TPartGroupLoadingQueue&, unsigned int, NKikimr::NTable::NPage::EPage) () [contrib/ydb/core/tablet_flat/flat_fwd_env.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_fwd_env.h?#L276) +276
4NKikimr::NTable::NFwd::TEnv::TryGetPage(NKikimr::NTable::TPart const*, unsigned int, NKikimr::NTable::NPage::TGroupId) () [contrib/ydb/core/tablet_flat/flat_fwd_env.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_fwd_env.h?#L134) +134
5NKikimr::NTable::TPartGroupBtreeIndexIter::Next() () [contrib/ydb/core/tablet_flat/flat_part_index_iter_bree_index.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_part_index_iter_bree_index.h?#L363) +363
6NKikimr::NTable::TPartGroupKeyIter::Seek(TArrayRef<NKikimr::TCell const>, NKikimr::NTable::ESeek, NKikimr::NTable::TPartScheme::TGroupInfo const&, NKikimr::NTable::TKeyCellDefaults const*) () [contrib/ydb/core/tablet_flat/flat_part_iter.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_part_iter.h?#L192) +192
7NKikimr::NTable::TRunIter::Seek(TArrayRef<NKikimr::TCell const>, NKikimr::NTable::ESeek) () [contrib/ydb/core/tablet_flat/flat_part_iter.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_part_iter.h?#L817) +817
8NKikimr::NTabletFlatExecutor::NOps::TDriver::React() () [contrib/ydb/core/tablet_flat/flat_scan_feed.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_scan_feed.h?#L405) +405
9NKikimr::NTabletFlatExecutor::NOps::TDriver::StateWork(TAutoPtr<NActors::IEventHandle, TDelete>&) () [contrib/ydb/core/tablet_flat/flat_scan_actor.h](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/core/tablet_flat/flat_scan_actor.h?#L649) +649
10NActors::TGenericExecutorThread::TProcessingResult NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::THTSwapMailbox>(NActors::TMailboxTable::THTSwapMailbox*, unsigned int, bool) () [contrib/ydb/library/actors/core/executor_thread.cpp](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/library/actors/core/executor_thread.cpp?#L251) +251
11NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const () [contrib/ydb/library/actors/core/executor_thread.cpp](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/library/actors/core/executor_thread.cpp?#L440) +440
12NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*) () [contrib/ydb/library/actors/core/executor_thread.cpp](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/library/actors/core/executor_thread.cpp?#L493) +493
13NActors::TExecutorThread::ThreadProc() () [contrib/ydb/library/actors/core/executor_thread.cpp](https://a.yandex-team.ru/arc/trunk/arcadia/contrib/ydb/library/actors/core/executor_thread.cpp?#L524) +524
14(anonymous namespace)::TPosixThread::ThreadProxy(void*) () [util/system/thread.cpp](https://a.yandex-team.ru/arc/trunk/arcadia/util/system/thread.cpp?#L244) +244
15?? () libpthread-2.31.so
16?? () libc-2.31.so
```

### PR DESCRIPTION
**Pull request by kungasc**
### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

Fixes #18151

Check the next page is within the slice bounds before calling `Index.Next()` method

### CODE REVIEW

File: ydb/core/tablet_flat/flat_fwd_cache.h [hunk 1]
```diff
@@ -279,6 +279,7 @@ namespace NFwd {
             TDeque<TPageEx> Pages;
             ui32 PagesBeginOffset = 0, PagesPendingOffset = 0;
             TDeque<TNodeState> Queue;
+            TPageId BeginPageId = Max<TPageId>(), EndPageId = 0;
```
Comment (kunga) [inline ydb/core/tablet_flat/flat_fwd_cache.h:282]: are needed just for clear error message

**Review by snaury — APPROVED** [review]
