### PR TITLE
Fix empty consumer name bug

### LINKED ISSUE #31743: Empty consumer in transfer export
При экспорте трансферов, если при их создании явно не указывалось имя консумера, в результате оно будет пустым, что не позволит его восстановить через выполнение SQL запроса

### PR DESCRIPTION
**Pull request by maybenotilya**
### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

...

### CODE REVIEW

File: ydb/public/lib/ydb_cli/dump/util/replication_utils.cpp [hunk 1]
```diff
@@ -155,7 +155,9 @@ TString BuildCreateTransferQuery(
 
     const auto& connectionParams = desc.GetConnectionParams();
     AddConnectionOptions(connectionParams, options);
-    options.push_back(BuildOption("CONSUMER", Quote(desc.GetConsumerName())));
+    if (!desc.GetConsumerName().empty()) {
+        options.push_back(BuildOption("CONSUMER", Quote(desc.GetConsumerName())));
```
Comment (CyberROFL) [inline ydb/public/lib/ydb_cli/dump/util/replication_utils.cpp:159]: Вкусовщина, можно так:
```suggestion
    if (const auto& consumerName = desc.GetConsumerName(); !consumerName.empty()) {
        options.push_back(BuildOption("CONSUMER", Quote(consumerName)));
```

**Review by CyberROFL — APPROVED** [review]

**Review by pnv1 — APPROVED** [review]
