### PR TITLE
fix(kqp): allow inconsistent reads for stream lookup

### LINKED ISSUE #2454: Allow inconsistent reads for stream lookup

### PR DESCRIPTION
**Pull request by ulya-sidorina**

### CODE REVIEW

**Review by ssmike — APPROVED** [review]

File: ydb/core/kqp/ut/opt/kqp_sqlin_ut.cpp [hunk 1]
```diff
@@ -1016,11 +1016,7 @@ Y_UNIT_TEST_SUITE(KqpSqlIn) {
             CompareYson(R"([[[1u];["One"]]])", FormatResultSetYson(result.GetResultSet(0)));
 
             const Ydb::TableStats::QueryStats stats = NYdb::TProtoAccessor::GetProto(*result.GetStats());
-            if (serverSettings.AppConfig.GetTableServiceConfig().GetEnableKqpDataQueryStreamLookup()) {
-                UNIT_ASSERT_EQUAL_C(1, stats.query_phases_size(), stats.DebugString());
-            } else {
-                UNIT_ASSERT_EQUAL_C(2, stats.query_phases_size(), stats.DebugString());
-            }
+            UNIT_ASSERT_EQUAL_C(2, stats.query_phases_size(), stats.DebugString())
```
Comment (ulya-sidorina) [inline ydb/core/kqp/ut/opt/kqp_sqlin_ut.cpp:1019]: missing ;
