### PR TITLE
Fix sole command rollback

### LINKED ISSUE #31091: dstool cluster set --dry-run --enable-self-heal ignores --dry-run
The setting is still applied despite `--dry-run` argument is specified

### PR DESCRIPTION
**Pull request by rosik**
### Changelog entry 

Fix BSController handling `dstool cluster set --dry-run` used to ignore `--dry-run` option and produced side-effects 

### Changelog category 

* Bugfix 

### Description for reviewers 

- Close #31091

### CODE REVIEW

File: ydb/core/mind/bscontroller/config_cmd.cpp [hunk 1]
```diff
@@ -157,11 +170,11 @@ namespace NKikimr::NBsController {
                             Self->TryToRelocateBrokenDisksLocallyFirst = value;
                             db.Table<T>().Key(true).Update<T::TryToRelocateBrokenDisksLocallyFirst>(Self->TryToRelocateBrokenDisksLocallyFirst);
                         }
-                        return true;
+                        return;
                     }
 
                     default:
```
Comment (alexvru) [inline ydb/core/mind/bscontroller/config_cmd.cpp:183]: We must not reach this code, so its better to assert here.

File: ydb/core/mind/bscontroller/config_cmd.cpp [hunk 2]
```diff
@@ -170,18 +183,19 @@ namespace NKikimr::NBsController {
                 THPTimer timer;
 
                 // check if there is some special sole command
-                if (Cmd.CommandSize() == 1) {
-                    bool res = true;
+                if (Cmd.CommandSize() == 1 && IsSoleCommand(Cmd.GetCommand(0))) {
                     WrapCommand([&] {
-                        res = ExecuteSoleCommand(Cmd.GetCommand(0), txc);
+                        if (Cmd.GetRollback()) {
+                            Success = false;
```
Comment (alexvru) [inline ydb/core/mind/bscontroller/config_cmd.cpp]: I suggest removing copypaste of lines 282-285. Maybe use a lambda instead.

File: ydb/core/mind/bscontroller/config_cmd.cpp [hunk 3]
```diff
@@ -377,20 +391,22 @@ namespace NKikimr::NBsController {
...
+                        throw TExError() << "unsupported command " << static_cast<int>(cmd.GetCommandCase());
+
                     case NKikimrBlobStorage::TConfigRequest::TCommand::kEnableSelfHeal:
                     case NKikimrBlobStorage::TConfigRequest::TCommand::kEnableDonorMode:
                     case NKikimrBlobStorage::TConfigRequest::TCommand::kSetScrubPeriodicity:
                     case NKikimrBlobStorage::TConfigRequest::TCommand::kSetPDiskSpaceMarginPromille:
                     case NKikimrBlobStorage::TConfigRequest::TCommand::kUpdateSettings:
-                    case NKikimrBlobStorage::TConfigRequest::TCommand::COMMAND_NOT_SET:
-                        throw TExError() << "unsupported command";
+                        throw TExError() << "command must be sole";
```
Comment (alexvru) [inline ydb/core/mind/bscontroller/config_cmd.cpp]: Again, inconsistent with IsSoleCommand()

**Review by alexvru — CHANGES_REQUESTED** [review]

**Review by alexvru — APPROVED** [review]
