### PR TITLE
Fix UI error "Failed to resolve database"

### LINKED ISSUE #11153: error resolving database nodes for NBS tenant

### PR DESCRIPTION
**Pull request by StekPerepolnen**
### Changelog entry 

In 24-3, support for redirecting requests to dynodes was added. The fix adjusts the scenario where a redirect is not possible: instead of throwing a "Failed to resolve database" error, the request is processed locally on the node that received it.

### Changelog category 

* Improvement

### CODE REVIEW

File: ydb/core/viewer/json_pipe_req.cpp [hunk 1]
```diff
@@ -748,6 +748,12 @@ void TViewerPipeClient::RequestDone(ui32 requests) {
     }
 }
 
+void TViewerPipeClient::ResetAndBootstrap() {
```
Comment (adameat) [inline ydb/core/viewer/json_pipe_req.cpp:751]: why?!

Comment (StekPerepolnen) [reply ydb/core/viewer/json_pipe_req.cpp:751]: Simply calling Bootstrap is not an option, as it resets the Request counter. This manifests in some requests waiting for a timeout (10 seconds) before completing.

Implementing a clean solution for accurate Request counting quickly is challenging. Resetting the counter is the easiest approach.

**Review by adameat — APPROVED** [review]
