### PR TITLE
[datastrerams ut] Fix flaky ScalarFederativeWriting, SysViewColumnsValues, DropStreamingQueryDuringRetries tests

### LINKED ISSUE #33460: Mute ydb/core/kqp/ut/federated_query/datastreams 2 tests in main
Mute:
ydb/core/kqp/ut/federated_query/datastreams/KqpStreamingQueriesSysView.SysViewColumnsValues
ydb/core/kqp/ut/federated_query/datastreams/KqpFederatedQueryDatastreams.ScalarFederativeWriting

Branch:
main

**Add line to [muted_ya.txt](https://github.com/ydb-platform/ydb/blob/main/.github/config/muted_ya.txt):**
```
ydb/core/kqp/ut/federated_query/datastreams KqpStreamingQueriesSysView.SysViewColumnsValues
ydb/core/kqp/ut/federated_query/datastreams KqpFederatedQueryDatastreams.ScalarFederativeWriting
```

Owner: TEAM:@ydb-platform/fq

**Read more in [mute_rules.md](https://github.com/ydb-platform/ydb/blob/main/.github/config/mute_rules.md)**

**Summary history:** 
 KqpStreamingQueriesSysView.SysViewColumnsValues: Flaky(2026-02-02)->Passed(2026-02-05) last 1 days, at 2026-02-02:2026-02-05: success_rate 87.1%, p-61, f-9, m-0, s-0, total-70
KqpFederatedQueryDatastreams.ScalarFederativeWriting: Flaky(2026-02-03)->Passed(2026-02-05) last 1 days, at 2026-02-02:2026-02-05: success_rate 92.9%, p-39, f-3, m-0, s-0, total-42

**Test run history:** [link](https://datalens.yandex/34xnbsom67hcq?full_name=__in_ydb%2Fcore%2Fkqp%2Fut%2Ffederated_query%2Fdatastreams%2FKqpStreamingQueriesSysView.SysViewColumnsValues&full_name=__in_ydb%2Fcore%2Fkqp%2Fut%2Ffederated_query%2Fdatastreams%2FKqpFederatedQueryDatastreams.ScalarFederativeWriting&branch=main)

More info in [dashboard](https://datalens.yandex/4un3zdm0zcnyr)

### PR DESCRIPTION
**Pull request by yumkam**
Closes: #33460, #34693
### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

Also refactor tests a bit to improve failure messages (UNIT_ASSERT_STINGS_EQUAL and UNIT..._C for dumping failed comparisons)

### CODE REVIEW

File: ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp [hunk 1]
```diff
@@ -2155,7 +2155,42 @@ Y_UNIT_TEST_SUITE(KqpFederatedQueryDatastreams) {
     "value": 23333
   }
 ])";
-        UNIT_ASSERT_VALUES_EQUAL(GetSolomonMetrics(soLocation), expectedMetrics);
+
```
Comment (yumkam) [inline ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp:2159]: This is only non-refactoring part of test: order of metrics could vary from run to run

File: ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp [hunk 2]
```diff
@@ -4776,14 +4811,14 @@ Y_UNIT_TEST_SUITE(KqpStreamingQueriesDdl) {
         UNIT_ASSERT_VALUES_EQUAL(results.size(), 2);
 
         CheckScriptResult(results[0], 1, 1, [&](TResultSetParser& resultSet) {
-            UNIT_ASSERT_VALUES_EQUAL(resultSet.ColumnParser("B").GetUtf8(), "test-C");
+            UNIT_ASSERT_STRINGS_EQUAL(resultSet.ColumnParser("B").GetUtf8(), "test-C");
         });
 
         CheckScriptResult(results[1], 1, 1, [&](TResultSetParser& resultSet) {
-            UNIT_ASSERT_VALUES_EQUAL(resultSet.ColumnParser("C").GetString(), "test-D");
+            UNIT_ASSERT_STRINGS_EQUAL(resultSet.ColumnParser("C").GetString(), "test-D");
```
Comment (uzhastik) [inline ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp]: изменения кажутся бесполезными. старый макрос подходит для всех типов. новый макрос специфичен и полезен для длинных строк, как я понимаю. в тесте много маленьких строк

Comment (yumkam) [reply ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp]: Откатил; оставил функциональную часть фикса

File: ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp [hunk 3]
```diff
@@ -2155,7 +2155,42 @@ Y_UNIT_TEST_SUITE(KqpFederatedQueryDatastreams) {
...
+      ]
+    ],
+    "ts": 1741790439,
+    "value": 13333
+  }
+])";
+        auto results = GetSolomonMetrics(soLocation);
+        if (results != expectedMetrics2) {
+            UNIT_ASSERT_STRINGS_EQUAL(results, expectedMetrics);
+        }
```
[the remark this answers is not in the document]
Comment (yumkam) [reply ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp:2194]: Fortunately, there cannot be more than two permutations in this case

File: ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp [hunk 4]
```diff
@@ -5017,7 +5052,6 @@ Y_UNIT_TEST_SUITE(KqpStreamingQueriesSysView) {
             UNIT_ASSERT_VALUES_EQUAL(operation.Metadata().ExecStatus, EExecStatus::Running);
         }
 
-        failAt = TInstant::Now();
```
Comment (yumkam) [inline ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp:5020]: And here the second part: in this test query fails *once*, we should not move time forward

File: ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp [hunk 5]
```diff
@@ -4823,16 +4858,39 @@ Y_UNIT_TEST_SUITE(KqpStreamingQueriesDdl) {
...
+                if (auto issues = resultSet.ColumnParser("Issues").GetOptionalUtf8()) {
+                    Cerr << " Issues " << *issues;
+                }
+                Cerr << Endl;
             });
+            if (ok) {
+                break;
+            }
+            Sleep(TDuration::MilliSeconds(50 + (rng() % 100))); // 100+-50ms
         }
```
[the remark this answers is not in the document]
Comment (yumkam) [reply ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp:4895]: Relies on test infrastructure to kill stuck test

File: ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp [hunk 6]
```diff
@@ -4823,16 +4858,39 @@ Y_UNIT_TEST_SUITE(KqpStreamingQueriesDdl) {
...
             UNIT_ASSERT_VALUES_EQUAL(result.size(), 1);
-            CheckScriptResult(result[0], 2, 1, [&](TResultSetParser& resultSet) {
-                UNIT_ASSERT_GE(*resultSet.ColumnParser("RetryCount").GetOptionalUint64(), 1);
-                UNIT_ASSERT(*resultSet.ColumnParser("SuspendedUntil").GetOptionalTimestamp());
+            bool ok = false;
+            CheckScriptResult(result[0], 3, 1, [&](TResultSetParser& resultSet) {
+                Cerr << "Now " << TInstant::Now();
+                if (auto suspendedUntil = resultSet.ColumnParser("SuspendedUntil").GetOptionalTimestamp()) {
+                    Cerr << " SuspendedUntil " << *suspendedUntil;
+                    ok = *suspendedUntil > TInstant::Now() + TDuration::MilliSeconds(500);
```
[the remark this answers is not in the document]
Comment (yumkam) [reply ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp:4875]: Test remains a little flaky anyway, we rely on heuristics (that retry timeout is greater than 500ms and that we manage to stop query if we started at least 500ms early). So, I agree in general, but sorry, won't fix it here

**Review by uzhastik — APPROVED** [review]
