### PR TITLE
Fix flaky TLI tests: propagate VictimQuerySpanId for STATUS_LOCKS_BROKEN without TxLocks

### LINKED ISSUE #36414: Mute ydb/core/kqp/ut/tli/KqpTli.ManyUpsertsDeferredLock in main
Mute:
ydb/core/kqp/ut/tli/KqpTli.ManyUpsertsDeferredLock

Branch:
main

**Add line to [muted_ya.txt](https://github.com/ydb-platform/ydb/blob/main/.github/config/muted_ya.txt):**
```
ydb/core/kqp/ut/tli KqpTli.ManyUpsertsDeferredLock
```

Owner: TEAM:@ydb-platform/qp

**Read more in [mute_rules.md](https://github.com/ydb-platform/ydb/blob/main/.github/config/mute_rules.md)**

**Summary history:** 
 KqpTli.ManyUpsertsDeferredLock: Flaky(2026-03-20)->Passed(2026-03-22) last 1 days, at 2026-03-20:2026-03-23: success_rate 89.3%, p-25, f-3, m-0, s-0, total-28

**Test run history:** [link](https://datalens.yandex/34xnbsom67hcq?full_name=__in_ydb%2Fcore%2Fkqp%2Fut%2Ftli%2FKqpTli.ManyUpsertsDeferredLock&branch=main)

More info in [dashboard](https://datalens.yandex/4un3zdm0zcnyr)

### PR DESCRIPTION
**Pull request by azevaykin**
### Changelog entry 

When a datashard returns STATUS_LOCKS_BROKEN via the EnsureCurrentLock, OnUniqueConstrainException, or TSerializableIsolationException paths, the response does not include TxLocks. The KQP layer then fails to resolve VictimQuerySpanId from stored locks, resulting in a missing VictimQuerySpanId in the SessionActor TLI log.

Added DeferredVictimQuerySpanId field to TTxStats so the DataShard can pass the victim's span ID directly in these paths. The KQP helper reads it as a fallback when TxLocks-based lookup finds nothing.

Fixes: #36414

### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

...

### CODE REVIEW

**Review by nikvas0 — DISMISSED** [review]
kqp ok

File: ydb/core/tx/datashard/execute_write_unit.cpp [hunk 1]
```diff
@@ -52,6 +52,15 @@ class TExecuteWriteUnit : public TExecutionUnit {
         }
     }
 
+    void FillDeferredVictimQuerySpanId(ui64 lockTxId, ui64 querySpanId, NKikimrQueryStats::TTxStats* txStats) {
+        auto victimSpanId = lockTxId
+            ? DataShard.SysLocksTable().GetVictimQuerySpanIdForLock(lockTxId) : Nothing();
+        ui64 value = victimSpanId ? *victimSpanId : querySpanId;
```
Comment (ztlpn) [inline ydb/core/tx/datashard/execute_write_unit.cpp]: Не очень понятно, почему выбираем querySpanId, если victimSpanId не найден. Типа, запрос сам себя сломал?

File: ydb/core/tx/datashard/execute_write_unit.cpp [hunk 2]
```diff
@@ -42,6 +42,9 @@ class TExecuteWriteUnit : public TExecutionUnit {
     }
 
     void FillDeferredBreakerInfo(ui64 lockTxId, NKikimrQueryStats::TTxStats* txStats) {
```
Comment (ztlpn) [inline ydb/core/tx/datashard/execute_write_unit.cpp]: минор: можно переименовать просто в FillDeferredFields

**Review by ztlpn — DISMISSED** [review]

File: ydb/core/tx/datashard/execute_write_unit.cpp (hunk 2 above)
Comment (azevaykin) [reply ydb/core/tx/datashard/execute_write_unit.cpp]: 04bde1e9057936735d65e5e338a83c69e4b5a788

File: ydb/core/tx/datashard/execute_write_unit.cpp (hunk 1 above)
Comment (azevaykin) [reply ydb/core/tx/datashard/execute_write_unit.cpp]: 462de8001f999ac6fa6617ea07063e8af18c4daa

**Review by ztlpn — APPROVED** [review]

**Review by nikvas0 — APPROVED** [review]
kqp ok
