### PR TITLE
CalculateKeyBytes operator precedence fix

### LINKED ISSUE #4497: CalculateKeyBytes operator precedence fix
Metric "table.datashard.write.bytes" is calculated badly due to the operator precedence error.

### PR DESCRIPTION
**Pull request by azevaykin**
### Changelog entry 

Fix operator precedence error in CalculateKeyBytes & CalculateValueBytes

### Changelog category 

* Bugfix 

### Additional information

...

### CODE REVIEW

File: ydb/core/tx/datashard/datashard_user_db.cpp [hunk 1]
```diff
@@ -49,11 +49,11 @@ NTable::EReady TDataShardUserDb::SelectRow(
 }
 
 ui64 CalculateKeyBytes(const TArrayRef<const TRawTypeValue> key) {
-    return std::accumulate(key.begin(), key.end(), 0, [](ui64 bytes, const TRawTypeValue& value) { return bytes + value.IsEmpty() ? 1 : value.Size(); });
+    return std::accumulate(key.begin(), key.end(), 0ull, [](ui64 bytes, const TRawTypeValue& value) { return bytes + (value.IsEmpty() ? 1ull : value.Size()); });
```
Comment (snaury) [inline ydb/core/tx/datashard/datashard_user_db.cpp:52]: Please use a normal `for` loop here, these reducers are very hard to understand at a glance.

Comment (azevaykin) [reply ydb/core/tx/datashard/datashard_user_db.cpp]: Changed

**Review by snaury — APPROVED** [review]
