### PR TITLE
YQL-17567: Fix of INSERT with no columns specified

### LINKED ISSUE #1834: [PG][YT] INSERT INTO VALUES doesn't work without columns list
Reproduce in pgrun:

```
--!syntax_pg
create table A (id int not null primary key, val text);
insert into A values (1);
insert into A values (2, 'a');

\pset null '<null>'
select * from A;

drop table A;
```

The syntax works for YDB. YT query inserts nulls instead of values.

### PR DESCRIPTION
**Pull request by marsaly79**
### Changelog category 
* Bugfix

### CODE REVIEW

File: ydb/library/yql/providers/yt/provider/yql_yt_datasink_type_ann.cpp [hunk 1]
```diff
@@ -459,7 +459,12 @@ class TYtDataSinkTypeAnnotationTransformer : public TVisitorTransformerBase {
             auto pgSelect = TCoPgSelect(content);
             if (NCommon::NeedToRenamePgSelectColumns(pgSelect)) {
                 TExprNode::TPtr output;
-                bool result = NCommon::RenamePgSelectColumns(pgSelect, output, contentColumnOrder, ctx, *State_->Types);
+
+                const auto& columnOrder = (outTableInfo.RowSpec)
+                    ? outTableInfo.RowSpec->GetColumnOrder()
```
Comment (marsaly79) [inline ydb/library/yql/providers/yt/provider/yql_yt_datasink_type_ann.cpp:464]: The core fix is here

File: ydb/library/yql/providers/yt/provider/yql_yt_physical_optimize.cpp [hunk 2]
```diff
@@ -3400,6 +3400,13 @@ class TYtPhysicalOptProposalTransformer : public TOptimizeTransformerBase {
             return {};
         }
         TYtOutTableInfo outTable(outItemType, State_->Configuration->UseNativeYtTypes.Get().GetOrElse(DEFAULT_USE_NATIVE_YT_TYPES) ? NTCF_ALL : NTCF_NONE);
+
+        {
+            auto path = write.Table().Name().StringValue();
+            auto commitEpoch = TEpochInfo::Parse(write.Table().CommitEpoch().Ref()).GetOrElse(0);
+            auto dstRowSpec = State_->TablesData->GetTable(cluster, path, commitEpoch).RowSpec;
+            outTable.RowSpec->SetColumnOrder(dstRowSpec->GetColumnOrder());
```
Comment (marsaly79) [inline ydb/library/yql/providers/yt/provider/yql_yt_physical_optimize.cpp:3408]: Column order was previously lost here, so second and further INSERTs into the same table failed

File: ydb/library/yql/tools/pgrun/pgrun.cpp [hunk 3]
```diff
@@ -939,34 +944,48 @@ std::pair<TString, TString> GetYtTableDataPaths(const TFsPath& dataDir, const TS
...
+    rowSpec->SetType(typeNode->Cast<TStructExprType>());
+    rowSpec->SetColumnOrder(std::move(columnOrder));
+
+    NYT::TNode attrs = NYT::TNode::CreateMap();
+    rowSpec->FillAttrNode(attrs[YqlRowSpecAttribute], 0, false);
+
+    NYT::TNode spec;
+    rowSpec->FillCodecNode(spec[YqlRowSpecAttribute]);
+
+    attrs["schema"] = RowSpecToYTSchema(spec[YqlRowSpecAttribute], 0).ToNode();
```
Comment (marsaly79) [inline ydb/library/yql/tools/pgrun/pgrun.cpp:985]: Save column order on table creation

**Review by vitstn — APPROVED** [review]
