### PR TITLE
Some fixes for BATCH operations with index

### LINKED ISSUE #33128: Batch update lost snapshot
The command:
```
BATCH UPDATE big_ann_1b
SET embedding_bit = Untag(Knn::ToBinaryStringBit(Knn::FloatFromBinaryString(embedding)), "BitVector")
```

It runs for 5 minutes and gave an error:

```
Table id 202 lost snapshot at v1769931485230/18446744073709551615 shard 72075186224185948 with lowWatermark v1769931486157/0 (node# 50010 state# Ready)
```

### PR DESCRIPTION
**Pull request by dahbka-lis**
### Changelog entry 

- BATCH is disabled for vector indexes.
- BATCH is disabled for fulltext indexes.
- BATCH is disabled for unique without `EnableIndexStreamWrite`.
- Fix problems and lost parameters for BATCH operations with `EnableIndexStreamWrite`.

Problem: `BATCH UPDATE` is executed like basic `UPDATE`: #33128
...

### Changelog category 

* Bugfix 

### Description for reviewers 

...

### CODE REVIEW

File: ydb/core/kqp/opt/kqp_opt_kql.cpp [hunk 1]
```diff
@@ -1053,6 +1088,17 @@ TExprNode::TPtr HandleDeleteTable(const TKiDeleteTable& del, TExprContext& ctx,
         return nullptr;
     }
 
+    if (del.IsBatch() == "true") {
+        const bool enabledIndexStreamWrite = kqpCtx.Config->GetEnableIndexStreamWrite();
+        for (const auto& index : tableData.Metadata->Indexes) {
```
Comment (nikvas0) [inline ydb/core/kqp/opt/kqp_opt_kql.cpp]: Move check to function

**Review by nikvas0 — APPROVED** [review]
