### PR TITLE
Fix for #22152

### LINKED ISSUE #22152: Падение в NKikimr::NColumnShard::TMonitoringObjectsCounter<TProcessScope>::GetCounter().Val() == 4;fline=ut_simple.cpp simple reader с дедубликацией
ydb/core/tx/conveyor_composite/ut/CompositeConveyorTests.Test10xDistribution
https://storage.yandexcloud.net/ydb-gh-logs/ydb-platform/ydb/PR-check/16654464303/ya-x86-64/try_3/ya-test.html#FAIL

```
{I:6797};{S:15079};{N:136472};
{I:6797};{S:35196};{N:164894};
{I:6797};{S:35196};{N:244022};
{I:6797};{S:37751};{N:350645};
{I:7329};{S:50677};{N:491476};
{I:12452};{S:109202};{N:644388};
{I:22419};{S:216650};{N:765447};
{I:35604};{S:355978};{N:856178};
{I:69184};{S:499200};{N:923539};
{I:128835};{S:640024};{N:968629};
{I:206735};{S:778769};{N:996593};
{I:311579};{S:913446};{N:1000000};
{I:461589};{S:991108};{N:1000000};
{I:636390};{S:1000000};{N:1000000};
{I:783326};{S:1000000};{N:1000000};
{I:888026};{S:1000000};{N:1000000};
{I:957008};{S:1000000};{N:1000000};
{I:995434};{S:1000000};{N:1000000};
{I:1000000};{S:1000000};{N:1000000};
57us per task
18.026250s;13.025769s;11.025051s;
VERIFY failed (2025-07-31T19:35:25.070741Z): verification=NKikimr::NColumnShard::TMonitoringObjectsCounter<TProcessScope>::GetCounter().Val() == 4;fline=ut_simple.cpp:203;count=5;
  ydb/library/actors/core/log.cpp:855
  ~TVerifyFormattedRecordWriter(): requirement false failed
NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char>>, char const*, unsigned long)+438 (0xB5325E6)
NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...)+263 (0xB5295E7)
??+0 (0xC9D24F4)
TTestingExecutor::Execute()+3324 (0xB4107AC)
NTestSuiteCompositeConveyorTests::TTestCaseTest10xDistribution::Execute_(NUnitTest::TTestContext&)+28 (0xB40FA9C)
NTestSuiteCompositeConveyorTests::TCurrentTest::Execute()::'lambda'()::operator()() const+71 (0xB411AD7)
NUnitTest::TTestBase::Run(std::__y1::function<void ()>, TBasicString<char, std::__y1::char_traits<char>> const&, char const*, bool)+126 (0xB6CF47E)
NTestSuiteCompositeConveyorTests::TCurrentTest::Execute()+433 (0xB411331)
NUnitTest::TTestFactory::Execute()+803 (0xB6CFBF3)
NUnitTest::RunMain(int, char**)+3021 (0xB6DDF0D)
??+0 (0x7F001EC0BD90)
__libc_start_main+128 (0x7F001EC0BE40)
_start+41 (0xA54D029)
```

### PR DESCRIPTION
**Pull request by XJIE6**
### Changelog entry 

...

### Changelog category 

* Not for changelog (changelog entry is not required)

### Description for reviewers 

...

### CODE REVIEW

File: ydb/core/tx/conveyor_composite/ut/ut_simple.cpp [hunk 1]
```diff
@@ -199,8 +199,17 @@ class TTestingExecutor {
             sb << i << ";";
         }
         Cerr << sb << Endl;
-        Sleep(TDuration::Seconds(15));
-        AFL_VERIFY(NKikimr::NColumnShard::TMonitoringObjectsCounter<TProcessScope>::GetCounter().Val() == 5)("count", NKikimr::NColumnShard::TMonitoringObjectsCounter<TProcessScope>::GetCounter().Val());
+
+        int expected = 5;
```
Comment (dorooleg) [inline ydb/core/tx/conveyor_composite/ut/ut_simple.cpp:204]: Используй `DoWithRetry`, тут можно найти пример:
https://a.yandex-team.ru/arcadia/contrib/ydb/tests/fq/control_plane_storage/ydb_test_bootstrap.h?rev=r17192267#L149

**Review by dorooleg — APPROVED** [review]
