### PR TITLE
TLI system views

### LINKED ISSUE #11724: Top partitions by TLI
The goal:
To monitor Transaction Lock Invalidated (TLI) new sys_views should be added `top_partitions_by_tli_one_minute` and `top_partitions_by_tli_one_minute` . They would show the top partitions with broken locks.

We want to see statistics on partitions:
* the number of whole shared locks
* the number of locks
* the number of ranges
* the length of ranges in rows

### PR DESCRIPTION
**Pull request by azevaykin**
#### `partition_stats` system view
Add new cumulative fields to the existing `partition_stats` system view:
* `LocksAcquired` - the number of locks installed "per key range";
* `LocksWholeshard` - the number of installed locks "for the entire batch";
* `LocksBroken` - the number of broken locks.

#### `top_partitions_by_tli_one_*` system view
Add new `top_partitions_by_tli_one_hour` and `top_partitions_by_tli_one_minute` system views.

The views give out the top 10 partitions with a large number of broken locks.

### Changelog category 

* New feature

### Description for reviewers 

...

### CODE REVIEW

File: ydb/core/sys_view/processor/tx_init.cpp [hunk 1]
```diff
@@ -428,29 +434,46 @@ struct TSysViewProcessor::TTxInit : public TTxBase {
...
+                return l->GetCPUCores() == r->GetCPUCores() ?
+                    l->GetTabletId() < r->GetTabletId() : l->GetCPUCores() > r->GetCPUCores();
+            };
+
+            std::sort(Self->PartitionTopByCpuMinute.begin(), Self->PartitionTopByCpuMinute.end(), compareByCpu);
+            std::sort(Self->PartitionTopByCpuHour.begin(), Self->PartitionTopByCpuHour.end(), compareByCpu);
+
+            auto compareByTli = [] (const auto& l, const auto& r) {
                 return l->GetCPUCores() == r->GetCPUCores() ?
                     l->GetTabletId() < r->GetTabletId() : l->GetCPUCores() > r->GetCPUCores();
```
Comment (alexd65536) [inline ydb/core/sys_view/processor/tx_init.cpp:462]: здесь, вероятно, надо сравнивать не по CPUCores

Comment (azevaykin) [reply ydb/core/sys_view/processor/tx_init.cpp]: bb366ce57fe28c1ebde7dc40e7c53616ed83ff15

**Review by snaury — APPROVED** [review]

**Review by ijon — APPROVED** [review]
